# Generated by Django 5.2.15 on 2026-06-19 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='币种代码')),
                ('name', models.CharField(max_length=50, verbose_name='币种名称')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='符号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '币种',
                'verbose_name_plural': '币种',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='家庭名称')),
                ('base_currency', models.CharField(default='CNY', max_length=10, verbose_name='默认本位币')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
            ],
            options={
                'verbose_name': '家庭',
                'verbose_name_plural': '家庭',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=10, verbose_name='基准币种')),
                ('quote_currency', models.CharField(max_length=10, verbose_name='目标币种')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='汇率')),
                ('rate_date', models.DateField(verbose_name='日期')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='数据来源')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '汇率',
                'verbose_name_plural': '汇率',
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', 'rate_date'], name='family_core_base_cu_f884de_idx')],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'rate_date'), name='unique_exchange_rate_per_day')],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('member', '家庭成员'), ('viewer', '查看者')], default='member', max_length=20, verbose_name='角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family_core.family', verbose_name='所属家庭')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_member', to=settings.AUTH_USER_MODEL, verbose_name='登录用户')),
            ],
            options={
                'verbose_name': '家庭成员',
                'verbose_name_plural': '家庭成员',
                'indexes': [models.Index(fields=['family', 'role'], name='family_core_family__092151_idx'), models.Index(fields=['is_active'], name='family_core_is_acti_efc1a6_idx')],
            },
        ),
    ]
