# Generated by Django 5.2.15 on 2026-06-19 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family_core.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '账户地区',
                'verbose_name_plural': '账户地区',
                'ordering': ['display_order', 'name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('family', 'name'), name='unique_account_region_per_family')],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family_core.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '账户类型',
                'verbose_name_plural': '账户类型',
                'ordering': ['display_order', 'name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('family', 'name'), name='unique_account_type_per_family')],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family_core.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '资产类别',
                'verbose_name_plural': '资产类别',
                'ordering': ['display_order', 'name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('family', 'name'), name='unique_asset_category_per_family')],
            },
        ),
    ]
