# Generated by Django 5.2.15 on 2026-07-11 04:21

from django.db import migrations, models


def populate_account_type_codes(apps, schema_editor):
    AccountType = apps.get_model("family_core", "AccountType")
    known_codes = {
        "银行": "bank",
        "券商": "broker",
        "支付宝": "alipay",
        "微信": "wechat",
        "养老金": "pension",
    }
    for item in AccountType.objects.order_by("pk"):
        item.code = known_codes.get(item.name, f"account-type-{item.pk}")
        item.save(update_fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0004_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='code',
            field=models.SlugField(blank=True, verbose_name='稳定代码'),
        ),
        migrations.RunPython(populate_account_type_codes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='accounttype',
            constraint=models.UniqueConstraint(fields=('family', 'code'), name='unique_account_type_code_per_family'),
        ),
    ]
