# Generated by Django 5.2.16 on 2026-10-05 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='family_core.assetcategory', verbose_name='所属一级类别'),
        ),
        migrations.CreateModel(
            name='AssetClassificationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('model_label', models.CharField(max_length=100)),
                ('object_id', models.PositiveBigIntegerField()),
                ('old_category', models.JSONField(default=dict)),
                ('new_category', models.JSONField(default=dict)),
                ('plan_digest', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.family')),
            ],
            options={
                'verbose_name': '资产分类调整记录',
                'verbose_name_plural': '资产分类调整记录',
                'ordering': ['-created_at', 'pk'],
            },
        ),
    ]
