# Generated by Django 5.2.16 on 2026-09-26 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=250, verbose_name='作者')),
                ('visibility', models.CharField(choices=[('private', '仅自己'), ('family', '家庭共享')], default='private', max_length=10, verbose_name='可见范围')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='简介')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.family')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.familymember')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('original_name', models.CharField(max_length=255)),
                ('original_path', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('format', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('queued', '等待处理'), ('processing', '正在解析'), ('ready', '可阅读'), ('failed', '处理失败'), ('unsupported', '已保存，阅读暂未接入')], db_index=True, default='queued', max_length=15)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('normalized_path', models.CharField(blank=True, max_length=500)),
                ('normalizer_version', models.CharField(blank=True, max_length=40)),
                ('resources', models.JSONField(blank=True, default=dict)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('text_status', models.CharField(default='unknown', max_length=20)),
                ('lease', models.UUIDField(editable=False, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='reading.book')),
            ],
            options={
                'verbose_name': '图书文件',
                'verbose_name_plural': '图书文件',
            },
        ),
        migrations.CreateModel(
            name='ReadingImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='reading.bookfile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file_hash', models.CharField(max_length=64)),
                ('location', models.JSONField(default=dict)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='reading.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_core.familymember')),
            ],
            options={
                'verbose_name': '个人阅读位置',
                'verbose_name_plural': '个人阅读位置',
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['family', 'visibility'], name='reading_boo_family__575835_idx'),
        ),
        migrations.AddConstraint(
            model_name='readingposition',
            constraint=models.UniqueConstraint(fields=('book', 'member'), name='reading_position_member_book'),
        ),
        migrations.AddConstraint(
            model_name='readingposition',
            constraint=models.CheckConstraint(condition=models.Q(('progress__lte', 10000)), name='reading_progress_range'),
        ),
    ]
