# Generated by Django 5.2.16 on 2026-09-26 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0004_add_zhipu_vision_provider'),
        ('family_core', '0008_assetcategory_code_constraint'),
        ('knowledge', '0013_alter_knowledgesource_kind'),
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfile',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_hash', models.CharField(max_length=64)),
                ('normalizer_version', models.CharField(max_length=40)),
                ('anchor', models.JSONField()),
                ('quote', models.TextField(max_length=4000)),
                ('note', models.TextField(blank=True, max_length=10000)),
                ('visibility', models.CharField(choices=[('private', '仅自己'), ('family', '家庭共享')], default='private', max_length=10)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('text_matched', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.familymember')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='reading.book')),
            ],
            options={
                'verbose_name': '阅读批注',
                'verbose_name_plural': '阅读批注',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('body', models.TextField(max_length=5000)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='reading.annotation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.familymember')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ReadingArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('visibility', models.CharField(choices=[('private', '仅自己'), ('family', '家庭共享')], default='private', max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='reading.book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.familymember')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingAiJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', '等待确认范围'), ('queued', '等待生成'), ('running', '正在生成'), ('success', '生成完成'), ('failed', '生成失败'), ('cancelled', '已取消')], db_index=True, default='draft', max_length=15)),
                ('provider_snapshot', models.JSONField()),
                ('input_snapshot', models.JSONField()),
                ('input_hash', models.CharField(max_length=64)),
                ('estimated_tokens', models.PositiveIntegerField()),
                ('estimated_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('analysis_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ai_analysis.aianalysisrequest')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_jobs', to='reading.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.familymember')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_analysis.aiprovider')),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reading.readingartifact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingArtifactVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=250)),
                ('data', models.JSONField(default=dict)),
                ('original_path', models.CharField(blank=True, max_length=500)),
                ('original_name', models.CharField(blank=True, max_length=250)),
                ('sha256', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('external', '外部整理'), ('manual', '成员整理'), ('ai', 'AI 提炼')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='reading.readingartifact')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='readingartifact',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reading.readingartifactversion'),
        ),
        migrations.CreateModel(
            name='ReadingArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reading_archive', to='knowledge.knowledgedocument')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='archive', to='reading.readingartifactversion')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='计划名称')),
                ('target_date', models.DateField(verbose_name='目标日期')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.familymember')),
            ],
            options={
                'ordering': ['target_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=250, verbose_name='书名')),
                ('kind', models.CharField(choices=[('online', '在线图书'), ('paper', '纸质书'), ('external', '外部阅读')], max_length=20, verbose_name='阅读方式')),
                ('manual_progress', models.PositiveSmallIntegerField(default=0, verbose_name='手工进度（%）')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reading.book')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reading.readingplan')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='readingartifactversion',
            constraint=models.UniqueConstraint(fields=('artifact', 'number'), name='reading_artifact_version'),
        ),
        migrations.AddConstraint(
            model_name='readingartifactversion',
            constraint=models.UniqueConstraint(fields=('artifact', 'sha256'), name='reading_artifact_content'),
        ),
        migrations.AddConstraint(
            model_name='readingplanitem',
            constraint=models.CheckConstraint(condition=models.Q(('manual_progress__lte', 100)), name='reading_manual_progress_range'),
        ),
        migrations.AddConstraint(
            model_name='readingplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'book'), name='reading_plan_unique_book'),
        ),
    ]
