# Generated by Django 5.2.17 on 2026-10-02 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('reading', '0004_remove_hidden_plain_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='移入回收站时间'),
        ),
        migrations.CreateModel(
            name='BookLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('delete', '移入回收站'), ('restore', '恢复图书')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.familymember')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='reading.book')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
