# Generated by Django 5.2.17 on 2026-10-02 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('reading', '0005_book_deleted_at_booklifecycleevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPurgeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book_id', models.UUIDField(unique=True)),
                ('title', models.CharField(max_length=250)),
                ('directories', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', '等待清理'), ('failed', '清理失败'), ('success', '已永久删除')], default='queued', max_length=10)),
                ('error', models.CharField(blank=True, max_length=250)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.familymember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
