# Generated by Django 5.2.17 on 2026-10-02 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0006_bookpurgetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingarchive',
            name='version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive', to='reading.readingartifactversion'),
        ),
    ]
