# Generated by Django 5.2.15 on 2026-08-13 01:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_type', models.CharField(choices=[('official_site', '官方网站'), ('rss', 'RSS / Atom'), ('x', 'X'), ('youtube', 'YouTube'), ('sec', 'SEC EDGAR'), ('media', '媒体'), ('manual', '人工录入')], max_length=30, verbose_name='来源类型')),
                ('adapter_key', models.SlugField(default='manual', verbose_name='适配器代码')),
                ('name', models.CharField(max_length=200, verbose_name='来源名称')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='来源入口')),
                ('external_id', models.CharField(blank=True, max_length=300, verbose_name='平台外部 ID')),
                ('source_tier', models.CharField(choices=[('A', 'A - 官方一手'), ('B', 'B - 直接采访/演讲'), ('C', 'C - 可信二手报道'), ('D', 'D - 发现线索')], default='C', max_length=1, verbose_name='来源等级')),
                ('transport_weight', models.PositiveSmallIntegerField(default=100, help_text='同一可信度下用于区分官网、官方社交账号等载体的信噪比。', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='载体权重')),
                ('poll_interval_minutes', models.PositiveIntegerField(default=60, verbose_name='建议采集间隔（分钟）')),
                ('cursor', models.JSONField(blank=True, default=dict, verbose_name='增量游标')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='最近成功时间')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, verbose_name='连续失败次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
            ],
            options={
                'verbose_name': '情报信息源',
                'verbose_name_plural': '情报信息源',
                'ordering': ['subject__display_name', 'source_tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_kind', models.CharField(choices=[('collection', '来源采集'), ('processing', '条目处理'), ('digest', '简报生成'), ('manual', '人工录入')], max_length=20, verbose_name='运行类型')),
                ('status', models.CharField(choices=[('running', '执行中'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败')], default='running', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='运行参数')),
                ('discovered_count', models.PositiveIntegerField(default=0, verbose_name='发现数量')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='新增数量')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='更新数量')),
                ('ignored_count', models.PositiveIntegerField(default=0, verbose_name='忽略数量')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失败数量')),
                ('error_summary', models.TextField(blank=True, verbose_name='错误摘要')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_collection_runs', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_collection_runs', to='family_core.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '情报运行记录',
                'verbose_name_plural': '情报运行记录',
                'ordering': ['-started_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('channel', models.CharField(default='people', max_length=30, verbose_name='频道')),
                ('event_type', models.CharField(choices=[('statement', '发言与观点'), ('interview', '采访与演讲'), ('investment', '投资与持仓披露'), ('business', '产品、经营与资本配置'), ('organization', '任职、组织与人物关系'), ('policy', '政策与公共事务'), ('other', '其他重要动态')], max_length=30, verbose_name='事件类型')),
                ('title', models.CharField(max_length=500, verbose_name='事件标题')),
                ('occurred_at', models.DateTimeField(verbose_name='事件时间')),
                ('occurred_precision', models.CharField(choices=[('exact', '精确时间'), ('date', '仅日期'), ('estimated', '估计时间')], default='exact', max_length=20, verbose_name='时间精度')),
                ('summary', models.TextField(verbose_name='事实摘要')),
                ('why_it_matters', models.TextField(blank=True, verbose_name='为什么重要')),
                ('importance_score', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='重要性分数')),
                ('confidence_score', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='置信度')),
                ('change_type', models.CharField(choices=[('new', '新动向'), ('continued', '延续'), ('strengthened', '增强'), ('weakened', '弱化'), ('reversed', '转向'), ('unknown', '无法判断')], default='unknown', max_length=20, verbose_name='变化信号')),
                ('review_status', models.CharField(choices=[('published', '已发布'), ('pending', '待复核'), ('reviewed', '已复核'), ('ignored', '已忽略')], default='published', max_length=20, verbose_name='复核状态')),
                ('cluster_key', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='事件簇标识')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='首次发现时间')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最近发现时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intelligence_events', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_events', to='family_core.family', verbose_name='所属家庭')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_intelligence_events', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '情报事件',
                'verbose_name_plural': '情报事件',
                'ordering': ['-occurred_at', '-importance_score', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EventUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('bookmarked_at', models.DateTimeField(blank=True, null=True, verbose_name='收藏时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_event_states', to='family_core.familymember', verbose_name='家庭成员')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='intelligence.intelligenceevent', verbose_name='情报事件')),
            ],
            options={
                'verbose_name': '事件用户状态',
                'verbose_name_plural': '事件用户状态',
            },
        ),
        migrations.CreateModel(
            name='EventSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('speaker', '发言者'), ('subject', '事件主体'), ('investor', '投资者'), ('executive', '经营者'), ('mentioned', '被提及'), ('affected_organization', '受影响机构')], default='subject', max_length=30, verbose_name='事件角色')),
                ('confidence_score', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='关联置信度')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要对象')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_links', to='intelligence.intelligenceevent', verbose_name='情报事件')),
            ],
            options={
                'verbose_name': '事件关注对象',
                'verbose_name_plural': '事件关注对象',
            },
        ),
        migrations.CreateModel(
            name='CollectionRunItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', '执行中'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败')], max_length=20, verbose_name='状态')),
                ('discovered_count', models.PositiveIntegerField(default=0, verbose_name='发现数量')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='新增数量')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失败数量')),
                ('error_summary', models.TextField(blank=True, verbose_name='错误摘要')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_results', to='intelligence.collectionrun', verbose_name='运行记录')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_results', to='intelligence.intelligencesource', verbose_name='信息源')),
            ],
            options={
                'verbose_name': '情报来源运行明细',
                'verbose_name_plural': '情报来源运行明细',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('subject_type', models.CharField(choices=[('person', '人物'), ('organization', '机构')], max_length=20, verbose_name='对象类型')),
                ('canonical_name', models.CharField(max_length=200, unique=True, verbose_name='规范名称')),
                ('display_name', models.CharField(max_length=200, verbose_name='显示名称')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='稳定标识')),
                ('aliases', models.JSONField(blank=True, default=list, verbose_name='别名')),
                ('category', models.CharField(choices=[('tech_leader', '科技领袖'), ('investor', '投资人'), ('policy_leader', '政策人物'), ('organization', '机构'), ('other', '其他')], max_length=30, verbose_name='类别')),
                ('profile_summary', models.TextField(blank=True, verbose_name='简介')),
                ('avatar_url', models.URLField(blank=True, max_length=1000, verbose_name='头像链接')),
                ('importance_level', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='重要性等级')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
            ],
            options={
                'verbose_name': '情报关注对象',
                'verbose_name_plural': '情报关注对象',
                'ordering': ['-importance_level', 'display_name', 'pk'],
                'indexes': [models.Index(fields=['subject_type', 'category', 'is_active'], name='intelligenc_subject_6c152f_idx')],
            },
        ),
        migrations.AddField(
            model_name='intelligencesource',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='intelligence.intelligencesubject', verbose_name='关注对象'),
        ),
        migrations.AddField(
            model_name='intelligenceevent',
            name='subjects',
            field=models.ManyToManyField(related_name='intelligence_events', through='intelligence.EventSubject', to='intelligence.intelligencesubject'),
        ),
        migrations.AddField(
            model_name='eventsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_links', to='intelligence.intelligencesubject', verbose_name='关注对象'),
        ),
        migrations.CreateModel(
            name='SourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('external_id', models.CharField(blank=True, max_length=300, verbose_name='平台条目 ID')),
                ('canonical_url', models.URLField(blank=True, max_length=1000, verbose_name='原文链接')),
                ('title', models.CharField(max_length=500, verbose_name='原始标题')),
                ('author_name', models.CharField(blank=True, max_length=200, verbose_name='发布者')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='采集时间')),
                ('language', models.CharField(blank=True, max_length=20, verbose_name='原文语言')),
                ('excerpt', models.TextField(blank=True, verbose_name='短摘录')),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='内容指纹')),
                ('raw_metadata', models.JSONField(blank=True, default=dict, verbose_name='来源元数据')),
                ('processing_status', models.CharField(choices=[('pending', '待处理'), ('clustered', '已聚类'), ('analyzed', '已分析'), ('failed', '处理失败'), ('ignored', '已忽略')], default='pending', max_length=20, verbose_name='处理状态')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intelligence_source_items', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='intelligence.intelligencesource', verbose_name='信息源')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_intelligence_source_items', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '情报来源条目',
                'verbose_name_plural': '情报来源条目',
                'ordering': ['-published_at', '-fetched_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='intelligenceevent',
            name='primary_source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_events', to='intelligence.sourceitem', verbose_name='主来源条目'),
        ),
        migrations.CreateModel(
            name='EventEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('evidence_type', models.CharField(choices=[('fact', '事实证据'), ('opinion', '观点证据'), ('context', '背景材料')], default='fact', max_length=20, verbose_name='证据类型')),
                ('excerpt', models.TextField(blank=True, verbose_name='证据摘录')),
                ('claim_ref', models.CharField(blank=True, max_length=100, verbose_name='支持的陈述 ID')),
                ('source_quality_score', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='来源质量分')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要证据')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='intelligence.intelligenceevent', verbose_name='情报事件')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_evidence_links', to='intelligence.sourceitem', verbose_name='来源条目')),
            ],
            options={
                'verbose_name': '事件证据',
                'verbose_name_plural': '事件证据',
            },
        ),
        migrations.CreateModel(
            name='SubjectFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('priority', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='关注优先级')),
                ('is_muted', models.BooleanField(default=False, verbose_name='静音')),
                ('is_active', models.BooleanField(default=True, verbose_name='正在关注')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_intelligence_subject_follows', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_subject_follows', to='family_core.family', verbose_name='所属家庭')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_follows', to='intelligence.intelligencesubject', verbose_name='关注对象')),
            ],
            options={
                'verbose_name': '家庭关注对象',
                'verbose_name_plural': '家庭关注对象',
            },
        ),
        migrations.CreateModel(
            name='SubjectRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('relation_type', models.CharField(choices=[('leadership', '任职'), ('founder', '创办'), ('investor', '投资'), ('affiliation', '关联'), ('other', '其他')], max_length=30, verbose_name='关系类型')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('evidence_note', models.TextField(blank=True, verbose_name='依据说明')),
                ('from_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='intelligence.intelligencesubject', verbose_name='起始对象')),
                ('to_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='intelligence.intelligencesubject', verbose_name='目标对象')),
            ],
            options={
                'verbose_name': '关注对象关系',
                'verbose_name_plural': '关注对象关系',
            },
        ),
        migrations.AddIndex(
            model_name='collectionrun',
            index=models.Index(fields=['family', 'run_kind', 'status', 'started_at'], name='intelligenc_family__bf1607_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventuserstate',
            constraint=models.UniqueConstraint(fields=('member', 'event'), name='unique_member_intelligence_event_state'),
        ),
        migrations.AddIndex(
            model_name='intelligencesource',
            index=models.Index(fields=['source_type', 'source_tier', 'is_active'], name='intelligenc_source__626a9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='intelligencesource',
            constraint=models.UniqueConstraint(fields=('subject', 'name'), name='unique_intelligence_source_name_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='eventsubject',
            constraint=models.UniqueConstraint(fields=('event', 'subject', 'role'), name='unique_intelligence_event_subject_role'),
        ),
        migrations.AddIndex(
            model_name='sourceitem',
            index=models.Index(fields=['source', 'published_at'], name='intelligenc_source__3789a4_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceitem',
            index=models.Index(fields=['processing_status', 'fetched_at'], name='intelligenc_process_5b2ed9_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='unique_intelligence_source_external_item'),
        ),
        migrations.AddIndex(
            model_name='intelligenceevent',
            index=models.Index(fields=['family', 'channel', 'review_status', 'occurred_at'], name='intelligenc_family__fbce12_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligenceevent',
            index=models.Index(fields=['event_type', 'importance_score'], name='intelligenc_event_t_1c8b62_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventevidence',
            constraint=models.UniqueConstraint(fields=('event', 'source_item'), name='unique_intelligence_event_source_item'),
        ),
        migrations.AddIndex(
            model_name='subjectfollow',
            index=models.Index(fields=['family', 'is_active', 'is_muted'], name='intelligenc_family__31c24e_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjectfollow',
            constraint=models.UniqueConstraint(fields=('family', 'subject'), name='unique_family_intelligence_subject_follow'),
        ),
        migrations.AddConstraint(
            model_name='subjectrelation',
            constraint=models.CheckConstraint(condition=models.Q(('from_subject', models.F('to_subject')), _negated=True), name='intelligence_relation_subjects_differ'),
        ),
        migrations.AddConstraint(
            model_name='subjectrelation',
            constraint=models.UniqueConstraint(fields=('from_subject', 'to_subject', 'relation_type'), name='unique_intelligence_subject_relation'),
        ),
    ]
