# Generated by Django 5.2.15 on 2026-08-13 04:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_topics_and_selection(apps, schema_editor):
    IntelligenceSource = apps.get_model('intelligence', 'IntelligenceSource')
    IntelligenceEvent = apps.get_model('intelligence', 'IntelligenceEvent')
    SourceItem = apps.get_model('intelligence', 'SourceItem')

    for source in IntelligenceSource.objects.exclude(subject_id=None).iterator():
        source.topics.add(source.subject_id)

    IntelligenceEvent.objects.filter(review_status='ignored').update(selection_status='noise')
    IntelligenceEvent.objects.filter(review_status='pending').update(selection_status='review')
    IntelligenceEvent.objects.filter(
        review_status__in=['published', 'reviewed'],
        importance_score__gte=75,
        confidence_score__gte=60,
    ).update(selection_status='selected')
    SourceItem.objects.filter(processing_status='clustered').update(
        processing_status='published',
        processing_reason='M1 人工记录迁移为已发布条目。',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intelligencesource',
            options={'ordering': ['source_tier', 'source_group', 'name'], 'verbose_name': '情报信息源', 'verbose_name_plural': '情报信息源'},
        ),
        migrations.AlterModelOptions(
            name='intelligencesubject',
            options={'ordering': ['-importance_level', 'display_name', 'pk'], 'verbose_name': '情报关注主题', 'verbose_name_plural': '情报关注主题'},
        ),
        migrations.AddField(
            model_name='collectionrun',
            name='classified_count',
            field=models.PositiveIntegerField(default=0, verbose_name='分类数量'),
        ),
        migrations.AddField(
            model_name='collectionrun',
            name='clustered_count',
            field=models.PositiveIntegerField(default=0, verbose_name='聚类数量'),
        ),
        migrations.AddField(
            model_name='collectionrun',
            name='noise_count',
            field=models.PositiveIntegerField(default=0, verbose_name='噪音数量'),
        ),
        migrations.AddField(
            model_name='collectionrun',
            name='normalized_count',
            field=models.PositiveIntegerField(default=0, verbose_name='标准化数量'),
        ),
        migrations.AddField(
            model_name='collectionrun',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='待复核数量'),
        ),
        migrations.AddField(
            model_name='collectionrun',
            name='selected_count',
            field=models.PositiveIntegerField(default=0, verbose_name='精选数量'),
        ),
        migrations.AddField(
            model_name='intelligenceevent',
            name='actionability_score',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='投资参考价值'),
        ),
        migrations.AddField(
            model_name='intelligenceevent',
            name='impact_score',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='影响程度'),
        ),
        migrations.AddField(
            model_name='intelligenceevent',
            name='novelty_score',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='新颖性'),
        ),
        migrations.AddField(
            model_name='intelligenceevent',
            name='relevance_score',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='相关性'),
        ),
        migrations.AddField(
            model_name='intelligenceevent',
            name='score_origin',
            field=models.CharField(choices=[('manual', '人工特征 + 代码评分'), ('rules', '规则特征 + 代码评分'), ('ai', 'AI 特征 + 代码评分')], default='manual', max_length=20, verbose_name='评分来源'),
        ),
        migrations.AddField(
            model_name='intelligenceevent',
            name='scoring_breakdown',
            field=models.JSONField(blank=True, default=dict, verbose_name='评分明细'),
        ),
        migrations.AddField(
            model_name='intelligenceevent',
            name='scoring_policy_version',
            field=models.CharField(default='people-v1', max_length=50, verbose_name='评分策略版本'),
        ),
        migrations.AddField(
            model_name='intelligenceevent',
            name='selection_status',
            field=models.CharField(choices=[('selected', '今日精选'), ('feed', '全部动态'), ('review', '待复核'), ('noise', '噪音箱')], default='feed', max_length=20, verbose_name='展示分层'),
        ),
        migrations.AddField(
            model_name='intelligenceevent',
            name='timeliness_score',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='时效性'),
        ),
        migrations.AddField(
            model_name='intelligencesource',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近尝试时间'),
        ),
        migrations.AddField(
            model_name='intelligencesource',
            name='last_error_summary',
            field=models.CharField(blank=True, max_length=500, verbose_name='最近错误摘要'),
        ),
        migrations.AddField(
            model_name='intelligencesource',
            name='source_group',
            field=models.CharField(choices=[('official', '官方网站与官方账号'), ('expert', '人物博客与访谈'), ('institution', '公司与研究机构'), ('media', '可信媒体'), ('social', '社交与视频平台'), ('regulatory', '监管与正式披露'), ('other', '其他')], default='other', max_length=30, verbose_name='信源类别'),
        ),
        migrations.AddField(
            model_name='intelligencesource',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='sources', to='intelligence.intelligencesubject', verbose_name='关联主题'),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='classification_labels',
            field=models.JSONField(blank=True, default=list, verbose_name='分类标签'),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='matched_subjects',
            field=models.ManyToManyField(blank=True, related_name='matched_source_items', to='intelligence.intelligencesubject', verbose_name='命中主题'),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理完成时间'),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='processing_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='处理说明'),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='relevance_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='相关性分数'),
        ),
        migrations.AlterField(
            model_name='intelligencesource',
            name='adapter_key',
            field=models.SlugField(choices=[('manual', '人工录入（已启用）'), ('rss', 'RSS / Atom（待 M2）'), ('youtube', 'YouTube（待 M2）'), ('sec', 'SEC EDGAR（待 M2）'), ('x', 'X API（待凭证确认）'), ('web', '公开网页（待 M2）')], default='manual', verbose_name='适配器代码'),
        ),
        migrations.AlterField(
            model_name='intelligencesource',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_sources', to='intelligence.intelligencesubject', verbose_name='主要关联主题'),
        ),
        migrations.AlterField(
            model_name='intelligencesubject',
            name='category',
            field=models.CharField(choices=[('tech_leader', '科技领袖'), ('investor', '投资人'), ('policy_leader', '政策人物'), ('organization', '机构'), ('industry', '行业主题'), ('technology', '技术主题'), ('policy', '政策主题'), ('security', '证券主题'), ('other', '其他')], max_length=30, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='intelligencesubject',
            name='subject_type',
            field=models.CharField(choices=[('person', '人物'), ('organization', '机构'), ('industry', '行业'), ('technology', '技术'), ('policy', '政策'), ('security', '证券'), ('topic', '通用主题')], max_length=20, verbose_name='对象类型'),
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='processing_status',
            field=models.CharField(choices=[('pending', '待处理'), ('normalized', '已标准化'), ('classified', '已分类'), ('scored', '已评分'), ('clustered', '已聚类'), ('analyzed', '已分析'), ('published', '已发布'), ('noise', '噪音箱'), ('failed', '处理失败'), ('ignored', '已忽略')], default='pending', max_length=20, verbose_name='处理状态'),
        ),
        migrations.AddIndex(
            model_name='intelligenceevent',
            index=models.Index(fields=['family', 'selection_status', 'occurred_at'], name='intelligenc_family__efeead_idx'),
        ),
        migrations.RunPython(backfill_topics_and_selection, migrations.RunPython.noop),
    ]
