# Generated by Django 5.2.15 on 2026-08-13 05:50

from django.db import migrations, models


def backfill_manual_content_depth(apps, schema_editor):
    SourceItem = apps.get_model('intelligence', 'SourceItem')
    SourceItem.objects.filter(source__adapter_key='manual').update(content_depth='manual')


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_alter_intelligencesource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrunitem',
            name='clustered_count',
            field=models.PositiveIntegerField(default=0, verbose_name='候选事件数量'),
        ),
        migrations.AddField(
            model_name='collectionrunitem',
            name='cursor_after',
            field=models.JSONField(blank=True, default=dict, verbose_name='采集后游标'),
        ),
        migrations.AddField(
            model_name='collectionrunitem',
            name='cursor_before',
            field=models.JSONField(blank=True, default=dict, verbose_name='采集前游标'),
        ),
        migrations.AddField(
            model_name='collectionrunitem',
            name='ignored_count',
            field=models.PositiveIntegerField(default=0, verbose_name='重复/未变化数量'),
        ),
        migrations.AddField(
            model_name='collectionrunitem',
            name='noise_count',
            field=models.PositiveIntegerField(default=0, verbose_name='噪音数量'),
        ),
        migrations.AddField(
            model_name='collectionrunitem',
            name='updated_count',
            field=models.PositiveIntegerField(default=0, verbose_name='更新数量'),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='content_depth',
            field=models.CharField(choices=[('title', '仅标题'), ('description', '标题与简介'), ('official_article', '官方文章正文'), ('transcript', '完整字幕/文字稿'), ('manual', '人工核查')], default='title', max_length=30, verbose_name='内容深度'),
        ),
        migrations.RunPython(backfill_manual_content_depth, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='intelligencesource',
            name='adapter_key',
            field=models.SlugField(choices=[('manual', '人工录入'), ('rss', 'RSS / Atom'), ('youtube', 'YouTube 官方频道（仅元数据）'), ('sec', 'SEC EDGAR（待后续阶段）'), ('x', 'X API（待凭证确认）'), ('web', '公开网页（待后续阶段）')], default='manual', verbose_name='适配器代码'),
        ),
        migrations.AddConstraint(
            model_name='intelligencesource',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('url', ''), _negated=True), models.Q(('adapter_key', 'manual'), _negated=True)), fields=('adapter_key', 'url'), name='unique_automatic_intelligence_source_url'),
        ),
    ]
