# Generated by Django 5.2.16 on 2026-08-16 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('intelligence', '0003_m2_collection_foundation'),
        ('knowledge', '0011_alter_knowledgesource_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventKnowledgeArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('archive_mode', models.CharField(choices=[('archive', '归档'), ('organize', '归档并加入待整理')], default='archive', max_length=20, verbose_name='归档方式')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_knowledge_archives', to='family_core.familymember', verbose_name='首次归档成员')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='intelligence_archive', to='knowledge.knowledgedocument', verbose_name='知识文档')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_archive', to='intelligence.intelligenceevent', verbose_name='情报事件')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_intelligence_knowledge_archives', to='family_core.familymember', verbose_name='最近调整成员')),
            ],
            options={
                'verbose_name': '情报知识归档',
                'verbose_name_plural': '情报知识归档',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SubjectKnowledgeIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author_name', models.CharField(max_length=300, verbose_name='知识库作者名称')),
                ('normalized_author_name', models.CharField(max_length=300, verbose_name='规范作者名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intelligence_knowledge_identities', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_knowledge_identities', to='family_core.family', verbose_name='所属家庭')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_identities', to='intelligence.intelligencesubject', verbose_name='关注对象')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_intelligence_knowledge_identities', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '人物知识身份映射',
                'verbose_name_plural': '人物知识身份映射',
                'ordering': ['author_name', 'pk'],
                'indexes': [models.Index(fields=['family', 'subject', 'is_active'], name='intelligenc_family__1fef3d_idx')],
                'constraints': [models.UniqueConstraint(fields=('family', 'normalized_author_name'), name='unique_intelligence_knowledge_author_per_family')],
            },
        ),
    ]
