# Generated by Django 5.2.16 on 2026-08-16 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0004_add_zhipu_vision_provider'),
        ('intelligence', '0004_eventknowledgearchive_subjectknowledgeidentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_name', models.CharField(blank=True, max_length=200, verbose_name='实际模型')),
                ('prompt_version', models.CharField(max_length=100, verbose_name='提示词版本')),
                ('schema_version', models.CharField(max_length=100, verbose_name='结构版本')),
                ('input_fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='输入指纹')),
                ('input_snapshot', models.JSONField(blank=True, default=dict, verbose_name='输入审计快照')),
                ('result_json', models.JSONField(blank=True, default=dict, verbose_name='结构化结果')),
                ('status', models.CharField(choices=[('pending', '处理中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误摘要')),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True, verbose_name='Token 用量')),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='费用估算')),
                ('is_current', models.BooleanField(default=False, verbose_name='当前采用版本')),
                ('analysis_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_event_analysis', to='ai_analysis.aianalysisrequest', verbose_name='AI 请求审计')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intelligence_event_analyses', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='intelligence.intelligenceevent', verbose_name='情报事件')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_event_analyses', to='ai_analysis.aiprovider', verbose_name='AI 服务商')),
            ],
            options={
                'verbose_name': '情报事件 AI 分析',
                'verbose_name_plural': '情报事件 AI 分析',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['event', 'status', 'created_at'], name='intelligenc_event_i_347cd2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('event',), name='unique_current_intelligence_event_analysis')],
            },
        ),
    ]
