# Generated by Django 5.2.16 on 2026-08-16 13:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('intelligence', '0005_eventanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligenceevent',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_duplicates', to='intelligence.intelligenceevent', verbose_name='已合并到事件'),
        ),
        migrations.CreateModel(
            name='EventMergeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='同事件置信分')),
                ('decision_band', models.CharField(choices=[('batch', '建议批量聚合'), ('review', '需要单项确认')], default='review', max_length=20, verbose_name='处理分层')),
                ('policy_version', models.CharField(max_length=100, verbose_name='建议策略版本')),
                ('reason', models.JSONField(blank=True, default=dict, verbose_name='建议依据')),
                ('auto_merge_eligible', models.BooleanField(default=False, verbose_name='达到未来自动聚合门槛')),
                ('requires_individual_review', models.BooleanField(default=True, verbose_name='必须单项确认')),
                ('status', models.CharField(choices=[('pending', '等待复核'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('stale', '已失效')], default='pending', max_length=20, verbose_name='建议状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_merge_suggestions', to='family_core.family', verbose_name='所属家庭')),
                ('left_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='left_merge_suggestions', to='intelligence.intelligenceevent', verbose_name='较小 ID 事件')),
                ('recommended_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommended_merge_suggestions', to='intelligence.intelligenceevent', verbose_name='建议保留事件')),
                ('recommended_primary_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommended_event_merge_suggestions', to='intelligence.sourceitem', verbose_name='建议主来源')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_intelligence_merge_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
                ('right_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='right_merge_suggestions', to='intelligence.intelligenceevent', verbose_name='较大 ID 事件')),
            ],
            options={
                'verbose_name': '同一事件建议',
                'verbose_name_plural': '同一事件建议',
                'ordering': ['-score', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EventMergeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('active', '已合并'), ('reverted', '已拆分')], default='active', max_length=20, verbose_name='合并状态')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='可逆操作快照')),
                ('merged_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='合并时间')),
                ('reverted_at', models.DateTimeField(blank=True, null=True, verbose_name='拆分时间')),
                ('canonical_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_merge_records', to='intelligence.intelligenceevent', verbose_name='保留事件')),
                ('duplicate_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_merge_records', to='intelligence.intelligenceevent', verbose_name='并入事件')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_event_merges', to='family_core.family', verbose_name='所属家庭')),
                ('merged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_intelligence_events', to=settings.AUTH_USER_MODEL, verbose_name='合并人')),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_intelligence_event_merges', to=settings.AUTH_USER_MODEL, verbose_name='拆分人')),
                ('suggestion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_record', to='intelligence.eventmergesuggestion', verbose_name='采用建议')),
            ],
            options={
                'verbose_name': '事件合并记录',
                'verbose_name_plural': '事件合并记录',
                'ordering': ['-merged_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='eventmergesuggestion',
            index=models.Index(fields=['family', 'status', 'decision_band', 'score'], name='intelligenc_family__c2ca62_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventmergesuggestion',
            constraint=models.UniqueConstraint(fields=('left_event', 'right_event', 'policy_version'), name='unique_intelligence_merge_suggestion_pair_policy'),
        ),
        migrations.AddIndex(
            model_name='eventmergerecord',
            index=models.Index(fields=['family', 'status', 'merged_at'], name='intelligenc_family__e662b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventmergerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('duplicate_event',), name='unique_active_intelligence_merge_duplicate'),
        ),
    ]
