# Generated by Django 5.2.16 on 2026-08-22 08:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('intelligence', '0006_intelligenceevent_merged_into_eventmergesuggestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('digest_date', models.DateField(verbose_name='简报日期')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('window_start', models.DateTimeField(verbose_name='窗口开始')),
                ('window_end', models.DateTimeField(verbose_name='窗口结束')),
                ('policy_version', models.CharField(default='daily-brief-v1', max_length=50, verbose_name='选取策略版本')),
                ('input_fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='输入指纹')),
                ('provider_names', models.JSONField(blank=True, default=list, verbose_name='采用模型')),
                ('analysis_count', models.PositiveIntegerField(default=0, verbose_name='采用分析数量')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='采用分析 Token 合计')),
                ('cost_estimate', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='采用分析费用估算')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生成时间')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_digests', to='family_core.family', verbose_name='所属家庭')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_intelligence_digests', to=settings.AUTH_USER_MODEL, verbose_name='生成人')),
            ],
            options={
                'verbose_name': 'AI 情报简报',
                'verbose_name_plural': 'AI 情报简报',
                'ordering': ['-digest_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceDigestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(choices=[('important', '今日重要'), ('follow_up', '值得跟进'), ('review', '待确认')], max_length=20, verbose_name='简报分组')),
                ('position', models.PositiveSmallIntegerField(verbose_name='组内顺序')),
                ('selection_reason', models.CharField(max_length=500, verbose_name='入选理由')),
                ('title_snapshot', models.CharField(max_length=500, verbose_name='标题快照')),
                ('summary_snapshot', models.TextField(verbose_name='摘要快照')),
                ('why_it_matters_snapshot', models.TextField(blank=True, verbose_name='重要性说明快照')),
                ('subject_names', models.JSONField(blank=True, default=list, verbose_name='关注对象快照')),
                ('source_name', models.CharField(blank=True, max_length=200, verbose_name='主来源快照')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='主来源链接快照')),
                ('occurred_at', models.DateTimeField(verbose_name='事件时间快照')),
                ('importance_score', models.PositiveSmallIntegerField(verbose_name='重要性快照')),
                ('confidence_score', models.PositiveSmallIntegerField(verbose_name='置信度快照')),
                ('evidence_refs', models.JSONField(blank=True, default=list, verbose_name='证据引用快照')),
                ('model_name_snapshot', models.CharField(blank=True, max_length=200, verbose_name='采用模型快照')),
                ('tokens_used_snapshot', models.PositiveIntegerField(default=0, verbose_name='Token 用量快照')),
                ('cost_estimate_snapshot', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='费用估算快照')),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digest_items', to='intelligence.eventanalysis', verbose_name='采用的 AI 分析')),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='intelligence.intelligencedigest', verbose_name='所属简报')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digest_items', to='intelligence.intelligenceevent', verbose_name='情报事件')),
            ],
            options={
                'verbose_name': 'AI 情报简报条目',
                'verbose_name_plural': 'AI 情报简报条目',
                'ordering': ['bucket', 'position', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='intelligencedigest',
            index=models.Index(fields=['family', 'digest_date'], name='intelligenc_family__796a8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='intelligencedigest',
            constraint=models.UniqueConstraint(fields=('family', 'digest_date'), name='unique_family_intelligence_digest_date'),
        ),
        migrations.AddConstraint(
            model_name='intelligencedigestitem',
            constraint=models.UniqueConstraint(fields=('digest', 'event'), name='unique_intelligence_digest_event'),
        ),
        migrations.AddConstraint(
            model_name='intelligencedigestitem',
            constraint=models.UniqueConstraint(fields=('digest', 'bucket', 'position'), name='unique_intelligence_digest_bucket_position'),
        ),
    ]
