# Generated by Django 5.2.17 on 2026-09-26 14:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0004_add_zhipu_vision_provider'),
        ('family_core', '0008_assetcategory_code_constraint'),
        ('intelligence', '0008_m4_1_article_evidence_and_automation'),
        ('knowledge', '0013_alter_knowledgesource_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('external_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('audio_url', models.URLField(blank=True, max_length=3000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('new', '待获取正文'), ('fetching', '正在获取'), ('asr_submit', '转写提交中'), ('asr_wait', '转写中'), ('text_ready', '文字稿可读'), ('summarizing', '正在整理'), ('ready', '整理完成'), ('failed', '需要处理'), ('uncertain', '提交结果待核对')], default='new', max_length=20)),
                ('requested', models.BooleanField(default=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=150)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('asr_reserved_cny', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('audio_file', models.FileField(blank=True, upload_to='intelligence/encrypted-audio/%Y/%m/')),
                ('audio_expires_at', models.DateTimeField(blank=True, null=True)),
                ('audio_mime', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['-published_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProgramRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content_hash', models.CharField(max_length=64)),
                ('origin', models.CharField(max_length=40)),
                ('source_url', models.URLField(max_length=2000)),
                ('text', models.TextField()),
                ('segments', models.JSONField(default=list)),
                ('provider_model', models.CharField(blank=True, max_length=100)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('summary_complete', models.BooleanField(default=False)),
                ('archived_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='knowledge.knowledgedocument')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='intelligence.programentry')),
            ],
        ),
        migrations.AddField(
            model_name='programentry',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='intelligence.programrevision'),
        ),
        migrations.CreateModel(
            name='ProgramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('encrypted_credentials', models.TextField(blank=True, editable=False)),
                ('workspace_id', models.CharField(blank=True, max_length=80)),
                ('public_base_url', models.URLField(blank=True)),
                ('allow_asr', models.BooleanField(default=False)),
                ('allow_summary', models.BooleanField(default=False)),
                ('monthly_asr_cny', models.DecimalField(decimal_places=2, default=20, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monthly_summary_usd', models.DecimalField(decimal_places=2, default=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_audio_minutes', models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)])),
                ('configured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='family_core.familymember')),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='family_core.family')),
                ('summary_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_analysis.aiprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('auto_process', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_core.family')),
            ],
        ),
        migrations.AddField(
            model_name='programentry',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='intelligence.programsubscription'),
        ),
        migrations.CreateModel(
            name='ProgramSummaryChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('result', models.JSONField(default=dict)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(default='program-summary-v1', max_length=40)),
                ('reserved_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_analysis.aiprovider')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='intelligence.programrevision')),
            ],
        ),
        migrations.AddConstraint(
            model_name='programrevision',
            constraint=models.UniqueConstraint(fields=('entry', 'content_hash'), name='unique_program_revision'),
        ),
        migrations.AddConstraint(
            model_name='programsubscription',
            constraint=models.UniqueConstraint(fields=('family', 'code'), name='unique_family_program'),
        ),
        migrations.AddConstraint(
            model_name='programentry',
            constraint=models.UniqueConstraint(fields=('subscription', 'external_id'), name='unique_program_entry'),
        ),
        migrations.AddConstraint(
            model_name='programsummarychunk',
            constraint=models.UniqueConstraint(fields=('revision', 'number'), name='unique_program_chunk'),
        ),
    ]
