# Generated by Django 5.2.17 on 2026-09-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0009_programentry_programrevision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programentry',
            name='state',
            field=models.CharField(choices=[('new', '待获取正文'), ('fetching', '正在获取'), ('asr_submit', '转写提交中'), ('asr_wait', '转写中'), ('text_ready', '文字稿可读'), ('summarizing', '正在整理'), ('ready', '整理完成'), ('waiting_config', '等待服务配置'), ('failed', '需要处理'), ('uncertain', '提交结果待核对')], default='new', max_length=20),
        ),
    ]
