# Generated by Django 5.2.16 on 2026-09-20 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('portfolio', '0028_optioncontract_is_adjusted_optioncontract_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('initial_thesis', models.TextField(verbose_name='原始持有理由')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_dossiers', to='family_core.family', verbose_name='所属家庭')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_dossiers', to='family_core.familymember', verbose_name='档案所有人')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_dossiers', to='portfolio.security', verbose_name='研究标的')),
            ],
            options={
                'verbose_name': '公司研究档案',
                'verbose_name_plural': '公司研究档案',
            },
        ),
        migrations.CreateModel(
            name='ResearchThesisRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(verbose_name='版本号')),
                ('thesis', models.TextField(verbose_name='当前判断')),
                ('pillars', models.JSONField(blank=True, default=list, verbose_name='关键假设')),
                ('questions', models.JSONField(blank=True, default=list, verbose_name='待验证问题')),
                ('change_reason', models.CharField(blank=True, max_length=500, verbose_name='修改原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_thesis_revisions', to='family_core.familymember', verbose_name='保存人')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='investment_research.researchdossier', verbose_name='所属档案')),
            ],
            options={
                'verbose_name': '判断版本',
                'verbose_name_plural': '判断版本',
                'ordering': ['-revision_number'],
            },
        ),
        migrations.AddField(
            model_name='researchdossier',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='investment_research.researchthesisrevision', verbose_name='当前判断版本'),
        ),
        migrations.AddConstraint(
            model_name='researchthesisrevision',
            constraint=models.UniqueConstraint(fields=('dossier', 'revision_number'), name='unique_thesis_revision_number_per_dossier'),
        ),
        migrations.AddConstraint(
            model_name='researchdossier',
            constraint=models.UniqueConstraint(fields=('owner', 'security'), name='unique_research_dossier_per_owner_security'),
        ),
    ]
