# Generated by Django 5.2.16 on 2026-09-20 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_research', '0001_initial'),
        ('portfolio', '0028_optioncontract_is_adjusted_optioncontract_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialResearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source', models.CharField(choices=[('sec', 'SEC EDGAR'), ('microsoft_ir', 'Microsoft IR')], max_length=32, verbose_name='来源')),
                ('external_id', models.CharField(max_length=255, verbose_name='来源内稳定标识')),
                ('document_type', models.CharField(choices=[('10-k', '10-K 年报'), ('10-q', '10-Q 季报'), ('8-k', '8-K 重大事件'), ('annual_report', '年度报告'), ('earnings_release', '财报新闻稿'), ('earnings_call', '财报电话会/网络直播'), ('investor_update', '投资者公告'), ('other', '其他')], max_length=32, verbose_name='资料类型')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('source_url', models.URLField(max_length=1000, verbose_name='来源链接')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='报告期截止日')),
                ('content_text', models.TextField(blank=True, null=True, verbose_name='正文纯文本')),
                ('content_sha256', models.CharField(blank=True, max_length=64, null=True, verbose_name='正文 SHA-256')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='抓取时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='来源元数据')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_research_documents', to='portfolio.security', verbose_name='所属证券')),
            ],
            options={
                'verbose_name': '官方研究资料',
                'verbose_name_plural': '官方研究资料',
                'ordering': ['-published_at', '-pk'],
                'indexes': [models.Index(fields=['security', '-published_at'], name='investment__securit_84c0b0_idx'), models.Index(fields=['source', 'document_type'], name='investment__source_e92b6b_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_official_document_source_external_id')],
            },
        ),
        migrations.CreateModel(
            name='ResearchSourceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source', models.CharField(choices=[('sec', 'SEC EDGAR'), ('microsoft_ir', 'Microsoft IR')], max_length=32, verbose_name='来源')),
                ('external_company_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='来源内公司标识')),
                ('cursor', models.JSONField(blank=True, default=dict, verbose_name='同步游标')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='最近检查时间')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='最近成功时间')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='最近错误')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_source_states', to='portfolio.security', verbose_name='所属证券')),
            ],
            options={
                'verbose_name': '来源同步状态',
                'verbose_name_plural': '来源同步状态',
                'constraints': [models.UniqueConstraint(fields=('security', 'source'), name='unique_research_source_state_security_source')],
            },
        ),
    ]
