# Generated by Django 5.2.16 on 2026-09-24 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('investment_research', '0005_research_metric_focus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchFilingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessments', models.JSONField(default=list, verbose_name='逐项假设与问题核查')),
                ('outcome', models.CharField(choices=[('supports', '总体支持'), ('weakens', '总体削弱'), ('mixed', '有支持也有反证'), ('unclear', '证据仍不足')], max_length=16, verbose_name='总体结果')),
                ('action', models.CharField(choices=[('keep', '暂时保持判断'), ('revise', '需要修订判断')], max_length=16, verbose_name='判断处理')),
                ('summary', models.TextField(verbose_name='本次复核结论')),
                ('follow_up', models.TextField(blank=True, verbose_name='后续待查')),
                ('citation', models.JSONField(blank=True, default=dict, verbose_name='固定原文引用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='复核时间')),
                ('content_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_reviews', to='investment_research.officialresearchcontentversion', verbose_name='引用正文版本')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_filing_reviews', to='family_core.familymember', verbose_name='复核人')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_reviews', to='investment_research.officialresearchdocument', verbose_name='复核财报')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filing_reviews', to='investment_research.researchdossier', verbose_name='研究档案')),
                ('thesis_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filing_reviews', to='investment_research.researchthesisrevision', verbose_name='复核时的判断')),
            ],
            options={
                'verbose_name': '财报复核',
                'verbose_name_plural': '财报复核',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['dossier', 'document', '-created_at'], name='investment__dossier_2beeac_idx')],
            },
        ),
    ]
