# Generated by Django 5.2.16 on 2026-09-24 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0010_align_request_field_defaults'),
        ('family_core', '0008_assetcategory_code_constraint'),
        ('investment_research', '0006_researchfilingreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchReviewPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list, verbose_name='已确认的核查事项')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='确认时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_review_plans', to='family_core.familymember', verbose_name='确认人')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_plans', to='investment_research.researchdossier', verbose_name='研究档案')),
                ('source_analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_research_review_plans', to='ai_analysis.aianalysisrequest', verbose_name='AI 草稿')),
                ('thesis_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_plans', to='investment_research.researchthesisrevision', verbose_name='判断版本')),
            ],
            options={
                'verbose_name': '财报复核计划',
                'verbose_name_plural': '财报复核计划',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['dossier', 'thesis_revision', '-created_at'], name='investment__dossier_991d01_idx')],
            },
        ),
    ]
