# Generated by Django 5.2.17 on 2026-09-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_research', '0007_researchreviewplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialresearchcontentversion',
            name='media_type',
            field=models.CharField(default='text/html', max_length=120, verbose_name='原件格式'),
        ),
        migrations.AddField(
            model_name='officialresearchcontentversion',
            name='sections',
            field=models.JSONField(blank=True, default=list, verbose_name='页码与正文位置'),
        ),
        migrations.AlterField(
            model_name='officialresearchcontentversion',
            name='raw_gzip',
            field=models.BinaryField(verbose_name='原始文件（gzip）'),
        ),
        migrations.AlterField(
            model_name='officialresearchdocument',
            name='document_type',
            field=models.CharField(choices=[('10-k', '10-K 年报'), ('10-q', '10-Q 季报'), ('8-k', '8-K 重大事件'), ('annual_report', '年度报告'), ('earnings_release', '财报新闻稿'), ('earnings_call', '财报电话会/网络直播'), ('investor_update', '投资者公告'), ('financial_statements', '财务报表'), ('presentation', '业绩演示材料'), ('prepared_remarks', '管理层演讲稿'), ('transcript', '电话会文字稿'), ('shareholder_letter', '股东信'), ('other', '其他')], max_length=32, verbose_name='资料类型'),
        ),
        migrations.AlterField(
            model_name='officialresearchdocument',
            name='source',
            field=models.CharField(choices=[('sec', 'SEC EDGAR'), ('microsoft_ir', 'Microsoft IR'), ('official_ir', '公司官方 IR')], max_length=32, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='researchsourcestate',
            name='source',
            field=models.CharField(choices=[('sec', 'SEC EDGAR'), ('microsoft_ir', 'Microsoft IR'), ('official_ir', '公司官方 IR')], max_length=32, verbose_name='来源'),
        ),
    ]
