# Generated by Django 5.2.17 on 2026-10-01 11:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_research', '0011_researchautodigestconsent'),
        ('portfolio', '0030_stockmarketresearchsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialresearchdocument',
            name='document_type',
            field=models.CharField(choices=[('10-k', '10-K 年报'), ('10-q', '10-Q 季报'), ('8-k', '8-K 重大事件'), ('20-f', '20-F 外国公司年报'), ('40-f', '40-F 加拿大公司年报'), ('6-k', '6-K 外国公司公告'), ('annual_report', '年度报告'), ('earnings_release', '财报新闻稿'), ('earnings_call', '财报电话会/网络直播'), ('investor_update', '投资者公告'), ('financial_statements', '财务报表'), ('presentation', '业绩演示材料'), ('prepared_remarks', '管理层演讲稿'), ('transcript', '电话会文字稿'), ('shareholder_letter', '股东信'), ('other', '其他')], max_length=32, verbose_name='资料类型'),
        ),
        migrations.CreateModel(
            name='CompanyAcquisitionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(default='queued', max_length=20)),
                ('selection', models.JSONField(default=list)),
                ('items', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acquisition_jobs', to='investment_research.researchdossier')),
            ],
            options={
                'verbose_name': '公司资料获取任务',
                'verbose_name_plural': '公司资料获取任务',
            },
        ),
        migrations.CreateModel(
            name='CompanyIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.JSONField(default=list)),
                ('listings', models.JSONField(default=list)),
                ('sec_ticker', models.CharField(blank=True, max_length=30)),
                ('cik', models.CharField(blank=True, max_length=10)),
                ('provenance', models.JSONField(default=dict)),
                ('security', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='research_identity', to='portfolio.security')),
            ],
            options={
                'verbose_name': '公司资料身份',
                'verbose_name_plural': '公司资料身份',
            },
        ),
        migrations.CreateModel(
            name='CompanyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('key', models.CharField(max_length=180)),
                ('kind', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=1500)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_materials', to='portfolio.security')),
            ],
            options={
                'verbose_name': '公司基础资料',
                'verbose_name_plural': '公司基础资料',
            },
        ),
        migrations.CreateModel(
            name='CompanyMaterialVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('raw_gzip', models.BinaryField()),
                ('sha256', models.CharField(max_length=64)),
                ('source_url', models.URLField(blank=True, max_length=1500)),
                ('media_type', models.CharField(default='application/json', max_length=80)),
                ('data', models.JSONField(default=dict)),
                ('text', models.TextField(blank=True)),
                ('report_date', models.CharField(blank=True, max_length=80)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='investment_research.companymaterial')),
            ],
            options={
                'verbose_name': '公司基础资料历史版本',
                'verbose_name_plural': '公司基础资料历史版本',
                'ordering': ['-number'],
            },
        ),
        migrations.AddConstraint(
            model_name='companymaterial',
            constraint=models.UniqueConstraint(fields=('security', 'key'), name='unique_company_material'),
        ),
        migrations.AddConstraint(
            model_name='companymaterialversion',
            constraint=models.UniqueConstraint(fields=('material', 'number'), name='unique_company_material_version'),
        ),
    ]
