# Generated by Django 5.2.17 on 2026-10-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_research', '0012_alter_officialresearchdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymaterial',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
