# Generated by Django 5.2.17 on 2026-10-01 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0011_module_model_defaults'),
        ('investment_research', '0013_companymaterial_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('questions', models.JSONField(default=list)),
                ('hypotheses', models.JSONField(default=list)),
                ('decision', models.CharField(choices=[('research', '继续研究'), ('watch', '加入观察'), ('pause', '暂不研究')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='preparation', to='ai_analysis.aianalysisrequest')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='investment_research.researchdossier')),
            ],
            options={
                'ordering': ['updated_at', 'pk'],
            },
        ),
    ]
