# Generated by Django 5.2.17 on 2026-10-03 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('investment_research', '0016_shared_research_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('instructions', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment_research.researchdossier')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_core.familymember')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'dossier'), name='unique_company_research_prompt'), models.UniqueConstraint(condition=models.Q(('dossier__isnull', True)), fields=('owner',), name='unique_default_research_prompt')],
            },
        ),
    ]
