# Generated by Django 5.2.17 on 2026-10-03 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0011_module_model_defaults'),
        ('family_core', '0008_assetcategory_code_constraint'),
        ('investment_research', '0018_approved_pro_report_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchautodigestconsent',
            name='daily_budget_usd',
            field=models.DecimalField(db_default='0.30', decimal_places=4, default='0.30', max_digits=9, verbose_name='自动分析每日费用上限'),
        ),
        migrations.AddField(
            model_name='researchdossier',
            name='question_list_revision',
            field=models.PositiveIntegerField(db_default=0, default=0, verbose_name='问题清单版本'),
        ),
        migrations.AddField(
            model_name='researchdossier',
            name='question_workflow',
            field=models.BooleanField(db_default=False, default=False, verbose_name='已采用问题清单流程'),
        ),
        migrations.AddField(
            model_name='researchdossier',
            name='research_paused',
            field=models.BooleanField(db_default=False, default=False, verbose_name='暂时结束研究'),
        ),
        migrations.CreateModel(
            name='ResearchQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=600, verbose_name='待跟踪问题')),
                ('supporting_condition', models.TextField(blank=True, verbose_name='什么证据会更相信')),
                ('reconsidering_condition', models.TextField(blank=True, verbose_name='什么证据会重新考虑')),
                ('metrics', models.TextField(blank=True, verbose_name='关注指标及口径')),
                ('source_notes', models.TextField(blank=True, verbose_name='指标来源')),
                ('status', models.CharField(choices=[('tracking', '跟踪中'), ('resolved', '已解决'), ('paused', '暂停'), ('removed', '已移出清单')], default='tracking', max_length=20, verbose_name='状态')),
                ('revision', models.PositiveIntegerField(default=1, verbose_name='问题版本')),
                ('position', models.PositiveIntegerField(default=0)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_questions', to='investment_research.researchdossier')),
                ('introduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_questions', to='ai_analysis.aianalysisrequest')),
            ],
            options={
                'verbose_name': '待跟踪问题',
                'verbose_name_plural': '待跟踪问题',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ResearchQuestionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.familymember')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='investment_research.researchquestion')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ResearchWorkflowSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('preferences', models.TextField(blank=True, verbose_name='通用研究偏好')),
                ('introduction_prompt', models.TextField(blank=True, verbose_name='初识报告高级提示词')),
                ('question_prompt', models.TextField(blank=True, verbose_name='问题建议高级提示词')),
                ('tracking_prompt', models.TextField(blank=True, verbose_name='问题跟踪高级提示词')),
                ('per_call_budget_usd', models.DecimalField(decimal_places=4, default='0.30', max_digits=9)),
                ('daily_budget_usd', models.DecimalField(decimal_places=4, default='0.30', max_digits=9)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='research_settings', to='family_core.familymember')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ai_analysis.aiprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchQuestionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.familymember')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='investment_research.researchquestion')),
            ],
            options={
                'ordering': ['-number'],
                'constraints': [models.UniqueConstraint(fields=('question', 'number'), name='unique_research_question_revision')],
            },
        ),
        migrations.CreateModel(
            name='ResearchQuestionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_revision', models.PositiveIntegerField()),
                ('answer', models.TextField()),
                ('change', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('strengthened', '证据增强'), ('weakened', '证据减弱'), ('unchanged', '未改变'), ('unresolved', '仍待核实')], max_length=20)),
                ('evidence', models.JSONField(default=list)),
                ('gap', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_updates', to='ai_analysis.aianalysisrequest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='investment_research.researchquestion')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('analysis', 'question'), name='unique_question_analysis_update')],
            },
        ),
        migrations.CreateModel(
            name='ResearchSupplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=1500)),
                ('original_name', models.CharField(blank=True, max_length=250)),
                ('media_type', models.CharField(blank=True, max_length=120)),
                ('raw_gzip', models.BinaryField()),
                ('sha256', models.CharField(max_length=64)),
                ('text', models.TextField(blank=True)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=1000)),
                ('extraction_note', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.familymember')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplements', to='investment_research.researchdossier')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('dossier', 'sha256'), name='unique_private_research_supplement')],
            },
        ),
    ]
