# Generated by Django 5.2.17 on 2026-10-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_research', '0019_researchautodigestconsent_daily_budget_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchautodigestconsent',
            name='provider_signature',
            field=models.CharField(blank=True, db_default='', default='', max_length=64, verbose_name='授权时模型配置校验'),
        ),
    ]
