# Generated by Django 5.2.15 on 2026-06-19 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bank_name', models.CharField(max_length=100, verbose_name='银行名称')),
                ('account_name', models.CharField(max_length=100, verbose_name='账户名称')),
                ('account_no_masked', models.CharField(blank=True, max_length=100, verbose_name='脱敏账号')),
                ('account_type', models.CharField(default='savings', max_length=30, verbose_name='账户类型')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='当前余额')),
                ('visibility', models.CharField(choices=[('private', '仅本人'), ('family', '家庭可见'), ('admin_only', '仅管理员')], default='private', max_length=20, verbose_name='可见范围')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='family_core.family', verbose_name='所属家庭')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='family_core.familymember', verbose_name='所属成员')),
            ],
            options={
                'verbose_name': '银行账户',
                'verbose_name_plural': '银行账户',
            },
        ),
        migrations.CreateModel(
            name='CashflowMonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('year', models.PositiveIntegerField(verbose_name='年')),
                ('month', models.PositiveIntegerField(verbose_name='月')),
                ('total_income', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='总收入')),
                ('total_expense', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='总支出')),
                ('net_cashflow', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='净现金流')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_summaries', to='family_core.family', verbose_name='所属家庭')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_summaries', to='family_core.familymember', verbose_name='所属成员')),
            ],
            options={
                'verbose_name': '月度现金流汇总',
                'verbose_name_plural': '月度现金流汇总',
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='family_core.family', verbose_name='所属家庭')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.expensecategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '支出分类',
                'verbose_name_plural': '支出分类',
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expense_date', models.DateField(verbose_name='支出日期')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='金额')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('merchant', models.CharField(blank=True, max_length=100, verbose_name='商户或对象')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='支付方式')),
                ('visibility', models.CharField(choices=[('private', '仅本人'), ('family', '家庭可见'), ('admin_only', '仅管理员')], default='private', max_length=20, verbose_name='可见范围')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_records', to='ledger.bankaccount', verbose_name='支出账户')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_records', to='ledger.expensecategory', verbose_name='支出分类')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_records', to='family_core.family', verbose_name='所属家庭')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_records', to='family_core.familymember', verbose_name='所属成员')),
            ],
            options={
                'verbose_name': '支出记录',
                'verbose_name_plural': '支出记录',
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_categories', to='family_core.family', verbose_name='所属家庭')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.incomecategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '收入分类',
                'verbose_name_plural': '收入分类',
            },
        ),
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('income_date', models.DateField(verbose_name='收入日期')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='金额')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('source_name', models.CharField(blank=True, max_length=100, verbose_name='来源')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='是否周期收入')),
                ('visibility', models.CharField(choices=[('private', '仅本人'), ('family', '家庭可见'), ('admin_only', '仅管理员')], default='private', max_length=20, verbose_name='可见范围')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='ledger.bankaccount', verbose_name='入账账户')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='ledger.incomecategory', verbose_name='收入分类')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_records', to='family_core.family', verbose_name='所属家庭')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_records', to='family_core.familymember', verbose_name='所属成员')),
            ],
            options={
                'verbose_name': '收入记录',
                'verbose_name_plural': '收入记录',
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['family', 'member'], name='ledger_bank_family__5eb4b7_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['bank_name'], name='ledger_bank_bank_na_d9b7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_active'], name='ledger_bank_is_acti_303baf_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowmonthlysummary',
            index=models.Index(fields=['family', 'member', 'year', 'month'], name='ledger_cash_family__760836_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashflowmonthlysummary',
            constraint=models.UniqueConstraint(fields=('family', 'member', 'year', 'month', 'currency'), name='unique_cashflow_monthly_summary'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('family', 'name', 'parent'), name='unique_expense_category'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['family', 'member', 'expense_date'], name='ledger_expe_family__ab9160_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['category'], name='ledger_expe_categor_a68045_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['bank_account'], name='ledger_expe_bank_ac_133601_idx'),
        ),
        migrations.AddConstraint(
            model_name='incomecategory',
            constraint=models.UniqueConstraint(fields=('family', 'name', 'parent'), name='unique_income_category'),
        ),
        migrations.AddIndex(
            model_name='incomerecord',
            index=models.Index(fields=['family', 'member', 'income_date'], name='ledger_inco_family__61bb10_idx'),
        ),
        migrations.AddIndex(
            model_name='incomerecord',
            index=models.Index(fields=['category'], name='ledger_inco_categor_8e8269_idx'),
        ),
        migrations.AddIndex(
            model_name='incomerecord',
            index=models.Index(fields=['bank_account'], name='ledger_inco_bank_ac_154236_idx'),
        ),
    ]
