# Generated by Django 5.2.15 on 2026-06-19 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('snapshot_date', models.DateField(verbose_name='快照日期')),
                ('base_currency', models.CharField(default='CNY', max_length=10, verbose_name='本位币')),
                ('usd_to_base', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='USD 汇率')),
                ('hkd_to_base', models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='HKD 汇率')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='标题')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_balance_snapshots', to='family_core.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '资产余额快照',
                'verbose_name_plural': '资产余额快照',
                'ordering': ['-snapshot_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetBalanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account_name', models.CharField(max_length=120, verbose_name='账户名称')),
                ('asset_category', models.CharField(max_length=120, verbose_name='账户资产类别')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('original_amount', models.DecimalField(decimal_places=4, default=0, max_digits=24, verbose_name='原币余额')),
                ('base_amount', models.DecimalField(decimal_places=4, default=0, max_digits=24, verbose_name='本位币余额')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_balance_entries', to='family_core.familymember', verbose_name='所属成员')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ledger.assetbalancesnapshot', verbose_name='资产余额快照')),
            ],
            options={
                'verbose_name': '资产余额明细',
                'verbose_name_plural': '资产余额明细',
                'ordering': ['display_order', 'account_name', 'asset_category', 'currency', 'member__display_name'],
            },
        ),
        migrations.AddIndex(
            model_name='assetbalancesnapshot',
            index=models.Index(fields=['family', 'snapshot_date'], name='ledger_asse_family__c4af9b_idx'),
        ),
        migrations.AddIndex(
            model_name='assetbalanceentry',
            index=models.Index(fields=['snapshot', 'account_name', 'asset_category', 'currency'], name='ledger_asse_snapsho_178803_idx'),
        ),
        migrations.AddIndex(
            model_name='assetbalanceentry',
            index=models.Index(fields=['member'], name='ledger_asse_member__fc045d_idx'),
        ),
    ]
