# Generated by Django 5.2.15 on 2026-06-19 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0002_accountregion_accounttype_assetcategory'),
        ('ledger', '0002_assetbalancesnapshot_assetbalanceentry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetbalanceentry',
            options={'ordering': ['display_order', 'account__account_name', 'asset_category__name', 'currency', 'member__display_name'], 'verbose_name': '资产余额明细', 'verbose_name_plural': '资产余额明细'},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': '账户', 'verbose_name_plural': '账户'},
        ),
        migrations.RemoveIndex(
            model_name='assetbalanceentry',
            name='ledger_asse_snapsho_178803_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankaccount',
            name='ledger_bank_bank_na_d9b7d6_idx',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='visibility',
        ),
        migrations.AddField(
            model_name='assetbalanceentry',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_balance_entries', to='ledger.bankaccount', verbose_name='账户名称'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='family_core.accountregion', verbose_name='账户地区'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='family_core.accounttype', verbose_name='账户类型'),
        ),
        migrations.AlterField(
            model_name='assetbalanceentry',
            name='account_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='账户名称备份'),
        ),
        migrations.AlterField(
            model_name='assetbalanceentry',
            name='asset_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_balance_entries', to='family_core.assetcategory', verbose_name='账户资产类别'),
        ),
        migrations.AddIndex(
            model_name='assetbalanceentry',
            index=models.Index(fields=['snapshot', 'account', 'asset_category', 'currency'], name='ledger_asse_snapsho_8f8260_idx'),
        ),
    ]
