# Generated by Django 5.2.15 on 2026-06-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0002_accountregion_accounttype_assetcategory'),
        ('ledger', '0003_alter_assetbalanceentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='统计结束日期'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='统计开始日期'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='统计结束日期'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='统计开始日期'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['family', 'member', 'period_start', 'period_end'], name='ledger_expe_family__2582cc_idx'),
        ),
        migrations.AddIndex(
            model_name='incomerecord',
            index=models.Index(fields=['family', 'member', 'period_start', 'period_end'], name='ledger_inco_family__d29684_idx'),
        ),
    ]
