# Generated by Django 5.2.15 on 2026-06-20 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0002_accountregion_accounttype_assetcategory'),
        ('ledger', '0004_expenserecord_period_end_expenserecord_period_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('year', models.PositiveIntegerField(verbose_name='预算年度')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_budgets', to='family_core.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '年度预算',
                'verbose_name_plural': '年度预算',
                'ordering': ['-year', 'family__name'],
            },
        ),
        migrations.CreateModel(
            name='AnnualBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('line_type', models.CharField(choices=[('income', '收入预算'), ('expense', '支出预算')], max_length=20, verbose_name='预算类型')),
                ('annual_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='年度预算金额')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.annualbudget', verbose_name='年度预算')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_budget_lines', to='ledger.expensecategory', verbose_name='支出分类')),
                ('income_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_budget_lines', to='ledger.incomecategory', verbose_name='收入分类')),
            ],
            options={
                'verbose_name': '年度预算明细',
                'verbose_name_plural': '年度预算明细',
                'ordering': ['line_type', 'income_category__name', 'expense_category__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='annualbudget',
            constraint=models.UniqueConstraint(fields=('family', 'year'), name='unique_annual_budget_per_family_year'),
        ),
        migrations.AddIndex(
            model_name='annualbudgetline',
            index=models.Index(fields=['budget', 'line_type'], name='ledger_annu_budget__1eea0e_idx'),
        ),
    ]
