# Generated by Django 5.2.15 on 2026-06-27 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0002_accountregion_accounttype_assetcategory'),
        ('ledger', '0005_annualbudget_annualbudgetline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='import_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='导入去重指纹'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='import_row_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='源文件行号'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支出时间'),
        ),
        migrations.CreateModel(
            name='ExpenseImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_filename', models.CharField(max_length=255, verbose_name='源文件名')),
                ('source_sha256', models.CharField(max_length=64, verbose_name='文件校验值')),
                ('worksheet_name', models.CharField(blank=True, max_length=255, verbose_name='工作表')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='源数据行数')),
                ('imported_count', models.PositiveIntegerField(default=0, verbose_name='新增行数')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='跳过重复行数')),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='源文件净支出')),
                ('status', models.CharField(choices=[('completed', '已完成')], default='completed', max_length=20, verbose_name='状态')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_import_batches', to='family_core.family', verbose_name='所属家庭')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='导入用户')),
            ],
            options={
                'verbose_name': '支出导入批次',
                'verbose_name_plural': '支出导入批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='ledger.expenseimportbatch', verbose_name='导入批次'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['import_batch', 'import_row_number'], name='ledger_expe_import__8195ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='expenserecord',
            constraint=models.UniqueConstraint(condition=models.Q(('import_fingerprint__isnull', False)), fields=('family', 'import_fingerprint'), name='unique_imported_expense_fingerprint'),
        ),
        migrations.AddIndex(
            model_name='expenseimportbatch',
            index=models.Index(fields=['family', 'created_at'], name='ledger_expe_family__e709a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='expenseimportbatch',
            constraint=models.UniqueConstraint(fields=('family', 'source_sha256'), name='unique_expense_import_file_per_family'),
        ),
    ]
