# Generated by Django 5.2.15 on 2026-07-11 04:21

from django.db import migrations, models


def populate_account_purposes(apps, schema_editor):
    BankAccount = apps.get_model("ledger", "BankAccount")
    HkIpoSubscriptionTrade = apps.get_model("ipo", "HkIpoSubscriptionTrade")
    ipo_account_ids = set(
        HkIpoSubscriptionTrade.objects.exclude(account_id=None).values_list(
            "account_id", flat=True
        )
    )
    for account in BankAccount.objects.select_related("account_type_ref"):
        supports_ipo = account.pk in ipo_account_ids or "打新账户" in (account.remark or "")
        supports_investment = supports_ipo or (
            account.account_type_ref
            and account.account_type_ref.code == "broker"
        )
        BankAccount.objects.filter(pk=account.pk).update(
            supports_investment=supports_investment,
            supports_ipo=supports_ipo,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0005_accounttype_code_and_more'),
        ('ipo', '0016_hkiposubscriptiontrade_created_by_and_more'),
        ('ledger', '0008_annualbudget_created_by_annualbudget_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='supports_investment',
            field=models.BooleanField(default=False, verbose_name='用于投资'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='supports_ipo',
            field=models.BooleanField(default=False, verbose_name='用于港股打新'),
        ),
        migrations.RunPython(populate_account_purposes, migrations.RunPython.noop),
    ]
