# Generated by Django 5.2.15 on 2026-07-21 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('ledger', '0009_bankaccount_supports_investment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentGoalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(default='家庭投资目标', max_length=120, verbose_name='方案名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='当前方案')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_goal_plans', to='family_core.family', verbose_name='所属家庭')),
                ('start_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_goal_plans', to='ledger.assetbalancesnapshot', verbose_name='期初资产快照')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '投资目标方案',
                'verbose_name_plural': '投资目标方案',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentGoalActualOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('target_date', models.DateField(verbose_name='目标日期')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=24, verbose_name='实际金额')),
                ('remark', models.TextField(blank=True, verbose_name='修正原因')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_goal_actual_overrides', to='family_core.familymember', verbose_name='家庭成员')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_overrides', to='ledger.investmentgoalplan', verbose_name='投资目标方案')),
            ],
            options={
                'verbose_name': '投资目标实际值修正',
                'verbose_name_plural': '投资目标实际值修正',
                'ordering': ['-target_date', 'member__display_order', 'member_id'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentGoalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('initial_amount', models.DecimalField(decimal_places=4, max_digits=24, verbose_name='期初资产')),
                ('semiannual_contribution', models.DecimalField(decimal_places=4, default=0, max_digits=24, verbose_name='每半年新增投入')),
                ('semiannual_return_rate', models.DecimalField(decimal_places=4, default=0, help_text='直接按半年计息，例如 6 表示每半年 6%。', max_digits=8, verbose_name='预期半年收益率（%）')),
                ('periods', models.PositiveIntegerField(default=24, help_text='期初之后的半年期数。', verbose_name='期数 N')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_goal_settings', to='family_core.familymember', verbose_name='家庭成员')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='ledger.investmentgoalplan', verbose_name='投资目标方案')),
            ],
            options={
                'verbose_name': '成员投资目标参数',
                'verbose_name_plural': '成员投资目标参数',
                'ordering': ['member__display_order', 'member_id'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentGoalPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('period_index', models.PositiveIntegerField(verbose_name='期次')),
                ('target_date', models.DateField(verbose_name='目标日期')),
                ('target_amount', models.DecimalField(decimal_places=4, max_digits=24, verbose_name='目标金额')),
                ('applied_contribution', models.DecimalField(decimal_places=4, default=0, max_digits=24, verbose_name='本期新增投入')),
                ('applied_return_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='本期收益率（%）')),
                ('is_frozen', models.BooleanField(default=False, verbose_name='已锁定')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='ledger.investmentgoalsetting', verbose_name='成员目标参数')),
            ],
            options={
                'verbose_name': '投资目标节点',
                'verbose_name_plural': '投资目标节点',
                'ordering': ['target_date', 'setting__member__display_order', 'setting__member_id'],
            },
        ),
        migrations.AddIndex(
            model_name='investmentgoalplan',
            index=models.Index(fields=['family', 'is_active'], name='ledger_inve_family__c92bdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='investmentgoalplan',
            constraint=models.UniqueConstraint(fields=('family', 'name'), name='unique_investment_goal_plan_name'),
        ),
        migrations.AddConstraint(
            model_name='investmentgoalactualoverride',
            constraint=models.UniqueConstraint(fields=('plan', 'member', 'target_date'), name='unique_investment_goal_actual_override'),
        ),
        migrations.AddConstraint(
            model_name='investmentgoalsetting',
            constraint=models.UniqueConstraint(fields=('plan', 'member'), name='unique_investment_goal_setting_member'),
        ),
        migrations.AddIndex(
            model_name='investmentgoalpoint',
            index=models.Index(fields=['target_date', 'is_frozen'], name='ledger_inve_target__9aefe4_idx'),
        ),
        migrations.AddConstraint(
            model_name='investmentgoalpoint',
            constraint=models.UniqueConstraint(fields=('setting', 'period_index'), name='unique_investment_goal_period'),
        ),
        migrations.AddConstraint(
            model_name='investmentgoalpoint',
            constraint=models.UniqueConstraint(fields=('setting', 'target_date'), name='unique_investment_goal_date'),
        ),
    ]
