# Generated by Django 5.2.15 on 2026-06-19 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('note_type', models.CharField(default='general', max_length=50, verbose_name='笔记类型')),
                ('visibility', models.CharField(default='private', max_length=20, verbose_name='可见范围')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI 总结')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_notes', to='family_core.family', verbose_name='所属家庭')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_notes', to='family_core.familymember', verbose_name='作者')),
            ],
            options={
                'verbose_name': '投资笔记',
                'verbose_name_plural': '投资笔记',
                'indexes': [models.Index(fields=['family', 'member', 'note_type', 'created_at'], name='notes_inves_family__6b6e39_idx')],
            },
        ),
    ]
