# Generated by Django 5.2.17 on 2026-09-30 02:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_analysis", "0011_module_model_defaults"),
        ("family_core", "0008_assetcategory_code_constraint"),
        ("investment_research", "0011_researchautodigestconsent"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerLease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("token", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="BudgetReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("input_key", models.CharField(max_length=64, unique=True)),
                ("reserved_cny", models.DecimalField(decimal_places=6, max_digits=12)),
                (
                    "actual_cny",
                    models.DecimalField(decimal_places=6, max_digits=12, null=True),
                ),
                ("status", models.CharField(default="reserved", max_length=20)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="family_core.family",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="family_core.familymember",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ai_analysis.aiprovider",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvestmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=500)),
                ("merge_reason", models.CharField(blank=True, max_length=500)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="family_core.family",
                    ),
                ),
                (
                    "merged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="family_core.familymember",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="investment_watch.investmentevent",
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="developments",
                        to="investment_watch.investmentevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField()),
                ("url", models.URLField(max_length=1000)),
                ("content_hash", models.CharField(max_length=64)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("found_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "有效"),
                            ("corrected", "已更正"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("market", models.CharField(default="全球", max_length=30)),
                ("category", models.CharField(default="公司", max_length=40)),
                ("topics", models.JSONField(default=list)),
                ("original_chain", models.CharField(max_length=100)),
                (
                    "official_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="investment_research.officialresearchcontentversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("saved", models.BooleanField(default=False)),
                ("read", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="investment_watch.investmentevent",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="family_core.familymember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("external_id", models.CharField(max_length=500)),
                (
                    "current_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="investment_watch.materialversion",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="investment_watch.investmentevent",
                    ),
                ),
                (
                    "official_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="investment_research.officialresearchdocument",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="materialversion",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="investment_watch.newsmaterial",
            ),
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.SlugField(max_length=80)),
                ("url", models.URLField(max_length=1000)),
                ("adapter", models.CharField(default="rss", max_length=30)),
                ("market", models.CharField(default="全球", max_length=30)),
                ("enabled", models.BooleanField(default=False)),
                ("interval_minutes", models.PositiveIntegerField(default=120)),
                ("max_items", models.PositiveIntegerField(default=40)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500)),
                ("cursor", models.JSONField(default=dict)),
                ("public_metadata_only", models.BooleanField(default=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="family_core.family",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="newsmaterial",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="materials",
                to="investment_watch.newssource",
            ),
        ),
        migrations.CreateModel(
            name="OperationReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.CharField(max_length=80)),
                ("key", models.CharField(max_length=100)),
                ("body_hash", models.CharField(max_length=64)),
                ("result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="family_core.familymember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("manual", models.BooleanField(default=False)),
                ("reason", models.CharField(max_length=500)),
                ("rule_version", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("selected_for_research", models.BooleanField(default=False)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_candidates",
                        to="investment_research.researchdossier",
                    ),
                ),
                (
                    "material_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="investment_watch.materialversion",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="investment_research.researchthesisrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThesisEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assumption_key", models.CharField(max_length=40)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("support", "有支持"),
                            ("weaken", "可能削弱"),
                            ("mixed", "影响有分歧"),
                            ("unknown", "证据不足"),
                        ],
                        max_length=20,
                    ),
                ),
                ("explanation", models.TextField()),
                ("quote", models.TextField(blank=True)),
                ("locator", models.CharField(blank=True, max_length=100)),
                ("conditions", models.TextField(blank=True)),
                ("gaps", models.TextField(blank=True)),
                ("method", models.CharField(default="model", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("input_key", models.CharField(max_length=64)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="investment_watch.researchcandidate",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="investment_research.researchthesisrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direction", models.CharField(max_length=20)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="family_core.familymember",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="investment_watch.thesisevidence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WatchConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("active", models.BooleanField(default=False)),
                ("provider_signature", models.CharField(max_length=64)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="family_core.familymember",
                    ),
                ),
                (
                    "dossier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="investment_research.researchdossier",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ai_analysis.aiprovider",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WatchRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("aliases", models.JSONField(default=list)),
                ("topics", models.JSONField(default=list)),
                ("include", models.JSONField(default=list)),
                ("exclude", models.JSONField(default=list)),
                ("enabled", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "dossier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="watch_rule",
                        to="investment_research.researchdossier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WatchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("input_key", models.CharField(max_length=64, unique=True)),
                ("status", models.CharField(default="queued", max_length=30)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="investment_research.researchdossier",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="investment_research.researchthesisrevision",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="investmentevent",
            constraint=models.UniqueConstraint(
                fields=("family", "fingerprint"), name="watch_event_fingerprint"
            ),
        ),
        migrations.AddConstraint(
            model_name="memberannotation",
            constraint=models.UniqueConstraint(
                fields=("member", "event"), name="watch_annotation_owner"
            ),
        ),
        migrations.AddIndex(
            model_name="materialversion",
            index=models.Index(
                fields=["-published_at", "-id"], name="watch_version_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="materialversion",
            constraint=models.UniqueConstraint(
                fields=("material", "number"), name="watch_material_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="newssource",
            constraint=models.UniqueConstraint(
                fields=("family", "key"), name="watch_source_family_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="newsmaterial",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="watch_material_identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationreceipt",
            constraint=models.UniqueConstraint(
                fields=("member", "operation", "key"), name="watch_operation_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchcandidate",
            constraint=models.UniqueConstraint(
                fields=("dossier", "material_version"), name="watch_candidate_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="thesisevidence",
            constraint=models.UniqueConstraint(
                fields=("input_key", "assumption_key"), name="watch_evidence_input"
            ),
        ),
    ]
