# Generated by Django 5.2.17 on 2026-09-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investment_research", "0011_researchautodigestconsent"),
        ("investment_watch", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="researchcandidate",
            name="watch_candidate_unique",
        ),
        migrations.AddConstraint(
            model_name="researchcandidate",
            constraint=models.UniqueConstraint(
                fields=("dossier", "material_version", "revision"),
                name="watch_candidate_unique",
            ),
        ),
    ]
