# Generated by Django 5.2.17 on 2026-09-30 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("family_core", "0008_assetcategory_code_constraint"),
        (
            "investment_watch",
            "0002_remove_researchcandidate_watch_candidate_unique_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=20)),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="investment_watch.investmentevent",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="family_core.familymember",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_actions",
                        to="investment_watch.investmentevent",
                    ),
                ),
            ],
        ),
    ]
