# Generated by Django 5.2.17 on 2026-09-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investment_watch", "0003_eventaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialversion",
            name="published_precision",
            field=models.CharField(default="time", max_length=12),
        ),
    ]
