# Generated by Django 5.2.17 on 2026-09-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investment_watch", "0004_materialversion_published_precision"),
    ]

    operations = [
        migrations.AddField(
            model_name="newssource",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
