# Generated by Django 5.2.17 on 2026-09-30 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("family_core", "0008_assetcategory_code_constraint"),
        ("investment_watch", "0005_newssource_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesisevidence",
            name="author_opinion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="thesisevidence",
            name="source_claim",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="MaterialRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("duplicate", "同一证据，无新增信息"),
                            ("followup", "新增进展"),
                            ("conflict", "存在矛盾"),
                            ("independent", "独立材料 / 撤销关系"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="family_core.familymember",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relation_history",
                        to="investment_watch.materialversion",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="related_reports",
                        to="investment_watch.materialversion",
                    ),
                ),
            ],
        ),
    ]
