# Generated by Django 5.2.17 on 2026-09-30 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investment_watch", "0006_thesisevidence_author_opinion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesisevidence",
            name="input_relation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="investment_watch.materialrelation",
            ),
        ),
    ]
