# Generated by Django 5.2.17 on 2026-10-02 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('investment_research', '0016_shared_research_archive'),
        ('investment_watch', '0007_thesisevidence_input_relation'),
        ('portfolio', '0030_stockmarketresearchsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('text', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('raw_gzip', models.BinaryField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(default='firecrawl-v2', max_length=30)),
                ('material_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='body_snapshot', to='investment_watch.materialversion')),
            ],
        ),
        migrations.AddField(
            model_name='thesisevidence',
            name='input_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='investment_watch.bodysnapshot'),
        ),
        migrations.CreateModel(
            name='ScreeningBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('input_key', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='reserved', max_length=20)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investment_research.researchdossier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_key', models.CharField(max_length=64, unique=True)),
                ('selected', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='investment_watch.researchcandidate')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investment_watch.screeningbatch')),
            ],
        ),
        migrations.CreateModel(
            name='WatchPipelineState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='family_core.family')),
            ],
        ),
        migrations.CreateModel(
            name='BodyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('day', models.DateField()),
                ('status', models.CharField(default='reserved', max_length=20)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investment_watch.researchcandidate')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.family')),
                ('material_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investment_watch.materialversion')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.security')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='investment_watch.bodysnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['family', 'security', 'day'], name='watch_body_daily')],
                'constraints': [models.UniqueConstraint(fields=('family', 'security', 'material_version'), name='watch_body_attempt_once')],
            },
        ),
    ]
