# Generated by Django 5.2.17 on 2026-10-02 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_watch', '0008_bodysnapshot_thesisevidence_input_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureAccountState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('checked_at', models.DateTimeField(null=True)),
                ('remaining', models.PositiveIntegerField(null=True)),
                ('plan_credits', models.PositiveIntegerField(null=True)),
                ('resets_at', models.DateTimeField(null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='candidatescreening',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reading_duplicates', to='investment_watch.researchcandidate'),
        ),
        migrations.AddField(
            model_name='candidatescreening',
            name='relevance',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='researchcandidate',
            name='reading_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='researchcandidate',
            name='reading_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchrule',
            name='business_context',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='watchrule',
            name='official_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='watchrule',
            name='products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
