# Generated by Django 5.2.17 on 2026-10-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_watch', '0010_msft_product_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newssource',
            name='last_added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newssource',
            name='last_result',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
