# Generated by Django 5.2.15 on 2026-06-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HkIpoListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, verbose_name='股票代码')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('listing_date', models.DateField(blank=True, null=True, verbose_name='上市日期')),
                ('status', models.CharField(default='upcoming', max_length=30, verbose_name='状态')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '港股新股',
                'verbose_name_plural': '港股新股',
            },
        ),
    ]
