# Generated by Django 5.2.15 on 2026-06-21 06:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hkipolisting',
            options={'ordering': ['-subscription_end_date', '-listing_date', 'stock_code'], 'verbose_name': '港股新股', 'verbose_name_plural': '港股新股'},
        ),
        migrations.RemoveField(
            model_name='hkipolisting',
            name='status',
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='allotment_result_date',
            field=models.DateField(blank=True, null=True, verbose_name='公布结果日'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='business_summary',
            field=models.TextField(blank=True, verbose_name='主要业务'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='comparable_companies',
            field=models.TextField(blank=True, verbose_name='同行业可比公司'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='cornerstone_investors',
            field=models.TextField(blank=True, verbose_name='基石投资者名单'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='cornerstone_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='基石占比'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='decision_reason',
            field=models.TextField(blank=True, verbose_name='决策理由'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='entry_fee',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='入场费'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='最终定价'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='fundamentals_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='基本面评分'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='fundraising_amount_100m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='募资金额（亿港元）'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='global_offer_shares_10k',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='全球发售股数（万股）'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='h_share_market_cap_100m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='H股市值（亿港元）'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='has_cornerstone',
            field=models.BooleanField(default=False, verbose_name='是否有基石投资者'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='has_greenshoe',
            field=models.BooleanField(default=False, verbose_name='绿鞋'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='has_offer_size_adjustment',
            field=models.BooleanField(default=False, verbose_name='发售量调整权'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='has_sponsor_dealer',
            field=models.CharField(blank=True, choices=[('yes', '有'), ('likely', '大概率'), ('unknown', '不确定'), ('market', '市场化')], max_length=20, verbose_name='是否有庄家'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='heat_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='热度评分'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='hk_connect_required_gain_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='港股通预期涨幅'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='hk_connect_threshold_100m',
            field=models.DecimalField(decimal_places=4, default=Decimal('105'), max_digits=20, verbose_name='港股通门槛（亿港元）'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='listing_type',
            field=models.CharField(choices=[('new_listing', '新上市'), ('ah', 'AH'), ('us_hk', '美港'), ('gem', '创业板'), ('other', '其他')], default='new_listing', max_length=30, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='lot_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='每手股数'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='mechanism',
            field=models.CharField(choices=[('a', '机制A'), ('b', '机制B'), ('18a', '18A'), ('18c', '18C')], default='a', max_length=20, verbose_name='机制'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='offer_price_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='招股价上限'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='offer_price_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='招股价下限'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='offer_size_adjustment_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='发售量调整比例'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='pe_ratio',
            field=models.CharField(blank=True, max_length=50, verbose_name='市盈率 PE'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='prospectus',
            field=models.FileField(blank=True, null=True, upload_to='ipo/prospectus/', verbose_name='招股书'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='ps_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='市销率 PS'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='public_offer_lots',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='公配手数'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='sector',
            field=models.CharField(blank=True, max_length=100, verbose_name='板块'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='sponsor',
            field=models.CharField(blank=True, max_length=200, verbose_name='保荐人'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='stabilizing_manager',
            field=models.CharField(blank=True, max_length=200, verbose_name='稳价人'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='招股截止日'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='subscription_recommendation',
            field=models.CharField(blank=True, choices=[('skip', '不认购'), ('cash_one_lot', '现金一手'), ('margin_one_lot', '融资一手'), ('pool_a', '甲组'), ('pool_b', '乙组')], max_length=30, verbose_name='认购建议'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='招股开始日'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='total_market_cap_100m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='发行后总市值（亿港元）'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='valuation_comment',
            field=models.CharField(blank=True, choices=[('low', '偏低'), ('reasonable', '合理'), ('high', '偏高'), ('expensive', '很贵')], max_length=30, verbose_name='估值评价'),
        ),
        migrations.AddIndex(
            model_name='hkipolisting',
            index=models.Index(fields=['stock_code'], name='ipo_hkipoli_stock_c_80f970_idx'),
        ),
        migrations.AddIndex(
            model_name='hkipolisting',
            index=models.Index(fields=['subscription_end_date'], name='ipo_hkipoli_subscri_87e518_idx'),
        ),
        migrations.AddIndex(
            model_name='hkipolisting',
            index=models.Index(fields=['listing_date'], name='ipo_hkipoli_listing_977344_idx'),
        ),
        migrations.AddIndex(
            model_name='hkipolisting',
            index=models.Index(fields=['listing_type'], name='ipo_hkipoli_listing_433cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='hkipolisting',
            index=models.Index(fields=['mechanism'], name='ipo_hkipoli_mechani_2cf084_idx'),
        ),
    ]
