# Generated by Django 5.2.15 on 2026-06-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0002_alter_hkipolisting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hkipolisting',
            name='stock_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='股票名称'),
        ),
        migrations.AddIndex(
            model_name='hkipolisting',
            index=models.Index(fields=['stock_name'], name='ipo_hkipoli_stock_n_51a31d_idx'),
        ),
    ]
