# Generated by Django 5.2.15 on 2026-06-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0003_hkipolisting_stock_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hkipolisting',
            name='subscription_status',
            field=models.CharField(choices=[('subscribing', '招股中'), ('waiting_listing', '待上市'), ('listing_today', '今日上市'), ('listed', '已上市')], default='listed', max_length=30, verbose_name='招股状态'),
        ),
        migrations.AddIndex(
            model_name='hkipolisting',
            index=models.Index(fields=['subscription_status'], name='ipo_hkipoli_subscri_78cced_idx'),
        ),
    ]
