# Generated by Django 5.2.15 on 2026-06-22 13:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0002_accountregion_accounttype_assetcategory'),
        ('ipo', '0004_hkipolisting_subscription_status_and_more'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HkIpoSubscriptionTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='申购日期')),
                ('tranche', models.CharField(choices=[('one_lot', '一手'), ('mid_a', '中甲'), ('tail_a', '甲尾'), ('head_b', '乙头'), ('b2', '乙2'), ('b3', '乙3'), ('large_b', '大乙')], default='one_lot', max_length=20, verbose_name='申购档位')),
                ('applied_lots', models.PositiveIntegerField(default=1, verbose_name='申购手数')),
                ('applied_shares', models.PositiveIntegerField(default=0, verbose_name='申购股数')),
                ('application_amount', models.DecimalField(decimal_places=4, default=0, max_digits=24, verbose_name='申购金额')),
                ('application_method', models.CharField(choices=[('cash', '现金'), ('margin', '融资')], default='margin', max_length=20, verbose_name='申购方式')),
                ('financing_amount', models.DecimalField(decimal_places=4, default=0, max_digits=24, verbose_name='融资金额')),
                ('financing_rate', models.DecimalField(decimal_places=4, default=Decimal('7'), max_digits=8, verbose_name='融资利率')),
                ('financing_days', models.PositiveIntegerField(default=1, verbose_name='融资天数')),
                ('financing_interest', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='融资利息')),
                ('subscription_fee', models.DecimalField(decimal_places=4, default=100, max_digits=20, verbose_name='手续费')),
                ('trade_status', models.CharField(choices=[('applying', '申购中'), ('holding', '尚持有'), ('closed', '清仓')], default='applying', max_length=20, verbose_name='新股状态')),
                ('allotted_lots', models.PositiveIntegerField(blank=True, null=True, verbose_name='中签手数')),
                ('allotted_value', models.DecimalField(decimal_places=4, default=0, max_digits=24, verbose_name='中签货值')),
                ('allotment_fee', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='中签费用')),
                ('sell_price', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='卖出金额')),
                ('sold_lots', models.PositiveIntegerField(default=0, verbose_name='卖出手数')),
                ('trading_fee', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='交易费用')),
                ('realized_profit', models.DecimalField(decimal_places=4, default=0, max_digits=24, verbose_name='盈利金额')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipo_subscription_trades', to='portfolio.investmentaccount', verbose_name='申购账户')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_trades', to='ipo.hkipolisting', verbose_name='对应新股')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipo_subscription_trades', to='family_core.familymember', verbose_name='家庭成员')),
            ],
            options={
                'verbose_name': '新股申购和交易',
                'verbose_name_plural': '新股申购和交易',
                'ordering': ['trade_status', '-application_date', 'listing__stock_code', 'account__account_name'],
                'indexes': [models.Index(fields=['listing', 'trade_status'], name='ipo_hkiposu_listing_741091_idx'), models.Index(fields=['member', 'trade_status'], name='ipo_hkiposu_member__eb706f_idx'), models.Index(fields=['account', 'trade_status'], name='ipo_hkiposu_account_ef7b5a_idx'), models.Index(fields=['application_date'], name='ipo_hkiposu_applica_bfac8d_idx')],
            },
        ),
    ]
