# Generated by Django 5.2.15 on 2026-06-22 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0005_hkiposubscriptiontrade'),
        ('ledger', '0005_annualbudget_annualbudgetline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hkiposubscriptiontrade',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipo_subscription_trades', to='ledger.bankaccount', verbose_name='申购账户'),
        ),
    ]
