# Generated by Django 5.2.15 on 2026-06-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0014_restore_nj1122_asset_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='hkipolisting',
            name='cumulative_change_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='上市至今累计涨幅'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='first_day_close_change_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='首日收盘涨幅'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='first_day_open_change_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='首日开盘涨幅'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='industry',
            field=models.CharField(blank=True, max_length=100, verbose_name='行业'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='market_data_fetched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上市行情静态数据抓取时间'),
        ),
        migrations.AddField(
            model_name='hkipolisting',
            name='over_subscription_multiple',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='超额认购倍数'),
        ),
    ]
