# Generated by Django 5.2.15 on 2026-06-19 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('broker_name', models.CharField(max_length=100, verbose_name='券商名称')),
                ('account_name', models.CharField(max_length=100, verbose_name='账户名称')),
                ('account_no_masked', models.CharField(blank=True, max_length=100, verbose_name='脱敏账号')),
                ('market_scope', models.CharField(blank=True, max_length=50, verbose_name='市场范围')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='主要币种')),
                ('cash_balance', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='现金余额')),
                ('visibility', models.CharField(choices=[('private', '仅本人'), ('family', '家庭可见'), ('admin_only', '仅管理员')], default='private', max_length=20, verbose_name='可见范围')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_accounts', to='family_core.family', verbose_name='所属家庭')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_accounts', to='family_core.familymember', verbose_name='所属成员')),
            ],
            options={
                'verbose_name': '投资账户',
                'verbose_name_plural': '投资账户',
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='快照日期')),
                ('total_cash', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='现金')),
                ('total_market_value', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='持仓市值')),
                ('total_asset', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='总资产')),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='总成本')),
                ('total_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='总盈亏')),
                ('pnl_ratio', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='盈亏比例')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolio.investmentaccount', verbose_name='投资账户')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to='family_core.family', verbose_name='所属家庭')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to='family_core.familymember', verbose_name='所属成员')),
            ],
            options={
                'verbose_name': '投资组合快照',
                'verbose_name_plural': '投资组合快照',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('symbol', models.CharField(max_length=30, verbose_name='代码')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('market', models.CharField(max_length=20, verbose_name='市场')),
                ('asset_type', models.CharField(default='stock', max_length=30, verbose_name='资产类型')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='交易币种')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='行业')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
            ],
            options={
                'verbose_name': '证券标的',
                'verbose_name_plural': '证券标的',
                'indexes': [models.Index(fields=['symbol', 'market'], name='portfolio_s_symbol_e75493_idx'), models.Index(fields=['asset_type'], name='portfolio_s_asset_t_47ccda_idx'), models.Index(fields=['is_active'], name='portfolio_s_is_acti_d531ca_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'market'), name='unique_security_symbol_market')],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('trade_date', models.DateField(verbose_name='交易日期')),
                ('trade_type', models.CharField(max_length=30, verbose_name='交易类型')),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=24, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='价格')),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='成交金额')),
                ('fee', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='手续费')),
                ('tax', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='税费')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('realized_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='已实现盈亏')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.investmentaccount', verbose_name='投资账户')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.security', verbose_name='证券标的')),
            ],
            options={
                'verbose_name': '投资交易记录',
                'verbose_name_plural': '投资交易记录',
            },
        ),
        migrations.CreateModel(
            name='InvestmentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=24, verbose_name='持仓数量')),
                ('avg_cost', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='平均成本')),
                ('current_price', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='当前价格')),
                ('market_value', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='当前市值')),
                ('unrealized_pnl', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='浮动盈亏')),
                ('pnl_ratio', models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='盈亏比例')),
                ('position_date', models.DateField(verbose_name='持仓日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.investmentaccount', verbose_name='投资账户')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.security', verbose_name='证券标的')),
            ],
            options={
                'verbose_name': '投资持仓',
                'verbose_name_plural': '投资持仓',
            },
        ),
        migrations.CreateModel(
            name='SecurityNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='新闻标题')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='链接')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='来源')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('sentiment', models.CharField(blank=True, max_length=20, verbose_name='情绪')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='portfolio.security', verbose_name='证券标的')),
            ],
            options={
                'verbose_name': '股票新闻缓存',
                'verbose_name_plural': '股票新闻缓存',
            },
        ),
        migrations.AddIndex(
            model_name='investmentaccount',
            index=models.Index(fields=['family', 'member'], name='portfolio_i_family__c95e94_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentaccount',
            index=models.Index(fields=['broker_name'], name='portfolio_i_broker__a01731_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentaccount',
            index=models.Index(fields=['is_active'], name='portfolio_i_is_acti_8a4dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['family', 'member', 'snapshot_date'], name='portfolio_p_family__b954c2_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['account', 'snapshot_date'], name='portfolio_p_account_4bab99_idx'),
        ),
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['account', 'trade_date'], name='portfolio_i_account_285a23_idx'),
        ),
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['security', 'trade_date'], name='portfolio_i_securit_3c405e_idx'),
        ),
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['trade_type'], name='portfolio_i_trade_t_5dd48b_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentposition',
            index=models.Index(fields=['account', 'security', 'position_date'], name='portfolio_i_account_964574_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentposition',
            index=models.Index(fields=['position_date'], name='portfolio_i_positio_b6442d_idx'),
        ),
        migrations.AddIndex(
            model_name='securitynews',
            index=models.Index(fields=['security', 'published_at'], name='portfolio_s_securit_d9c57f_idx'),
        ),
        migrations.AddIndex(
            model_name='securitynews',
            index=models.Index(fields=['source'], name='portfolio_s_source_84477c_idx'),
        ),
    ]
