# Generated by Django 5.2.15 on 2026-07-18 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_bankaccount_supports_investment_and_more'),
        ('portfolio', '0022_add_us_arca_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAccountBalanceAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('anchor_date', models.DateField(verbose_name='锚点日期')),
                ('currency', models.CharField(max_length=10, verbose_name='原币')),
                ('original_amount', models.DecimalField(decimal_places=4, max_digits=24, verbose_name='权威原币余额')),
                ('recorded_base_amount', models.DecimalField(decimal_places=4, max_digits=24, verbose_name='账本本位币余额')),
                ('reason', models.CharField(choices=[('historical_balance', '历史余额'), ('ledger_reconciliation', '家庭账本核对')], default='historical_balance', max_length=30, verbose_name='原因')),
                ('carry_forward', models.BooleanField(default=False, verbose_name='沿用至下一锚点')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='已确认')),
                ('remark', models.TextField(blank=True, verbose_name='说明')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_anchors', to='portfolio.investmentaccount', verbose_name='投资账户')),
                ('ledger_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_balance_anchors', to='ledger.assetbalancesnapshot', verbose_name='家庭账本资产快照')),
            ],
            options={
                'verbose_name': '投资账户余额锚点',
                'verbose_name_plural': '投资账户余额锚点',
                'ordering': ['-anchor_date', 'account_id', 'currency'],
                'indexes': [models.Index(fields=['account', 'anchor_date'], name='portfolio_p_account_eeff52_idx'), models.Index(fields=['anchor_date', 'is_confirmed'], name='portfolio_p_anchor__31c068_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'anchor_date', 'currency'), name='unique_portfolio_account_balance_anchor')],
            },
        ),
    ]
