# Generated by Django 5.2.16 on 2026-08-02 14:36

from datetime import datetime, time

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def set_option_price_validity_to_one_week(apps, schema_editor):
    SecurityQuoteConfig = apps.get_model("portfolio", "SecurityQuoteConfig")
    SecurityQuoteConfig.objects.filter(
        security__asset_type="option",
    ).update(max_age_hours=168)


def backfill_latest_option_transaction_prices(apps, schema_editor):
    InvestmentPosition = apps.get_model("portfolio", "InvestmentPosition")
    InvestmentTransaction = apps.get_model("portfolio", "InvestmentTransaction")
    SecurityMarketSnapshot = apps.get_model("portfolio", "SecurityMarketSnapshot")
    SecurityPriceRecord = apps.get_model("portfolio", "SecurityPriceRecord")

    positions = InvestmentPosition.objects.filter(
        security__asset_type="option",
    ).exclude(quantity=0)
    for position in positions.iterator():
        latest_trade = (
            InvestmentTransaction.objects.filter(
                account_id=position.account_id,
                security_id=position.security_id,
                status__in=["partial", "completed"],
                price__gte=0,
            )
            .order_by("-trade_date", "-created_at", "-pk")
            .first()
        )
        if not latest_trade:
            continue
        price_as_of = timezone.make_aware(
            datetime.combine(latest_trade.trade_date, time(16, 0))
        )
        if price_as_of > timezone.now():
            price_as_of = timezone.now()
        latest_price = (
            SecurityPriceRecord.objects.filter(security_id=position.security_id)
            .order_by("-price_as_of", "-pk")
            .first()
        )
        if latest_price and latest_price.price_as_of >= price_as_of:
            continue
        SecurityPriceRecord.objects.create(
            security_id=position.security_id,
            price=latest_trade.price,
            currency=latest_trade.currency,
            source="manual",
            price_type="transaction",
            price_as_of=price_as_of,
            raw_data={
                "transaction_id": latest_trade.pk,
                "transaction_price": True,
                "migration_backfill": True,
            },
        )
        snapshot, created = SecurityMarketSnapshot.objects.get_or_create(
            security_id=position.security_id,
            defaults={
                "quote_time": price_as_of.isoformat(),
                "last_price": latest_trade.price,
                "price_source": "manual",
                "price_as_of": price_as_of,
                "pricing_status": "manual",
                "last_attempt_at": timezone.now(),
                "raw_data": {"migration_backfill": True},
            },
        )
        if not created and (
            snapshot.price_as_of is None or snapshot.price_as_of < price_as_of
        ):
            snapshot.quote_time = price_as_of.isoformat()
            snapshot.last_price = latest_trade.price
            snapshot.price_source = "manual"
            snapshot.price_as_of = price_as_of
            snapshot.pricing_status = "manual"
            snapshot.last_attempt_at = timezone.now()
            snapshot.last_error = ""
            snapshot.save()
        InvestmentPosition.objects.filter(pk=position.pk).update(
            current_price=latest_trade.price,
            current_price_as_of=price_as_of,
            current_price_source="manual",
            pricing_status="manual",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('portfolio', '0026_snapshot_audit_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='显示顺序')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_groups', to='family_core.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '自选股分类',
                'verbose_name_plural': '自选股分类',
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='portfolio.watchlistgroup', verbose_name='自选分类'),
        ),
        migrations.AddConstraint(
            model_name='watchlistgroup',
            constraint=models.UniqueConstraint(fields=('family', 'name'), name='unique_family_watchlist_group_name'),
        ),
        migrations.RunPython(
            set_option_price_validity_to_one_week,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            backfill_latest_option_transaction_prices,
            migrations.RunPython.noop,
        ),
    ]
