# Generated by Django 5.2.16 on 2026-08-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_watchlistgroup_watchlistitem_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optioncontract',
            name='is_adjusted',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='是否调整合约'),
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='provider',
            field=models.CharField(blank=True, max_length=30, verbose_name='合约身份来源'),
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='provider_contract_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='行情源合约代码'),
        ),
        migrations.AddConstraint(
            model_name='optioncontract',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('provider', ''), _negated=True), models.Q(('provider_contract_code', ''), _negated=True)), fields=('provider', 'provider_contract_code'), name='unique_option_contract_provider_code'),
        ),
    ]
