# Generated by Django 5.2.16 on 2026-10-03 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_stockmarketresearchsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalValuationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('valuation_date', models.DateField(verbose_name='估值确认日期')),
                ('quote_date', models.DateField(verbose_name='原始报价日期')),
                ('price', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='确认估值价格')),
                ('currency', models.CharField(max_length=10, verbose_name='报价币种')),
                ('basis', models.CharField(choices=[('grey_market', '暗盘收盘价'), ('bond_clean', '债券净价（不含应计利息）'), ('suspended_close', '停牌前收盘价')], max_length=20, verbose_name='估值依据')),
                ('evidence', models.TextField(verbose_name='确认说明与来源')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.investmentaccount', verbose_name='投资账户')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.security', verbose_name='证券标的')),
            ],
            options={
                'verbose_name': '历史估值价格确认',
                'verbose_name_plural': '历史估值价格确认',
                'constraints': [models.UniqueConstraint(fields=('account', 'security', 'valuation_date'), name='unique_account_historical_price_review')],
            },
        ),
    ]
