# Generated by Django 5.2.16 on 2026-10-05 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0009_assetcategory_parent_assetclassificationaudit'),
        ('portfolio', '0031_historical_valuation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonddetail',
            name='original_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='原始发行日'),
        ),
        migrations.AddField(
            model_name='portfoliosnapshotpositionline',
            name='asset_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshot_position_lines', to='family_core.assetcategory', verbose_name='快照资产类别'),
        ),
        migrations.AlterField(
            model_name='security',
            name='asset_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='securities', to='family_core.assetcategory', verbose_name='二级资产类别'),
        ),
    ]
