# Generated by Django 5.2.17 on 2026-09-28 03:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_analysis', '0011_module_model_defaults'),
        ('family_core', '0008_assetcategory_code_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorState',
            fields=[
                ('key', models.CharField(default='main', max_length=30, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('message', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HostSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampled_at', models.DateTimeField(unique=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('proxy_ok', models.BooleanField(default=False)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('upload_total', models.PositiveBigIntegerField(null=True)),
                ('download_total', models.PositiveBigIntegerField(null=True)),
                ('upload_delta', models.PositiveBigIntegerField(null=True)),
                ('download_delta', models.PositiveBigIntegerField(null=True)),
                ('gap', models.BooleanField(default=False)),
                ('subscriptions', models.JSONField(default=list)),
                ('disk_total', models.PositiveBigIntegerField(null=True)),
                ('disk_free', models.PositiveBigIntegerField(null=True)),
                ('backup_at', models.DateTimeField(null=True)),
                ('backup_name', models.CharField(blank=True, max_length=200)),
                ('log_activity', models.JSONField(default=dict)),
                ('message', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'NAS 采集快照',
                'verbose_name_plural': 'NAS 采集快照',
                'ordering': ['-sampled_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_id', models.PositiveBigIntegerField()),
                ('source', models.CharField(max_length=60)),
                ('file_bytes', models.PositiveBigIntegerField()),
                ('media_type', models.CharField(max_length=40)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.family')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BalanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('deepseek', 'DeepSeek'), ('zhipu', '智谱'), ('volcano', '火山方舟'), ('ali', '阿里百炼'), ('other', '其他')], max_length=20)),
                ('account_key', models.CharField(default='default', max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('key_env', models.CharField(blank=True, max_length=100)),
                ('encrypted_credentials', models.TextField(blank=True, editable=False)),
                ('balance_cny', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('checked_at', models.DateTimeField(null=True)),
                ('attempted_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='unconfigured', max_length=20)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('low_threshold', models.DecimalField(decimal_places=2, default=20, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('refresh_requested', models.BooleanField(default=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.family')),
            ],
            options={
                'verbose_name': '服务商余额',
                'verbose_name_plural': '服务商余额',
                'constraints': [models.UniqueConstraint(fields=('family', 'vendor', 'account_key'), name='monitor_unique_account')],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor', models.CharField(choices=[('deepseek', 'DeepSeek'), ('zhipu', '智谱'), ('volcano', '火山方舟'), ('ali', '阿里百炼'), ('other', '其他')], max_length=20)),
                ('model_name', models.CharField(max_length=150)),
                ('module', models.CharField(max_length=40)),
                ('source_ref', models.CharField(blank=True, max_length=160)),
                ('vendor_request_id', models.CharField(blank=True, max_length=160)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('pending', '处理中'), ('confirmed', '已确认'), ('unknown', '用量未确认')], default='pending', max_length=16)),
                ('input_tokens', models.PositiveBigIntegerField(null=True)),
                ('output_tokens', models.PositiveBigIntegerField(null=True)),
                ('cached_tokens', models.PositiveBigIntegerField(null=True)),
                ('total_tokens', models.PositiveBigIntegerField(null=True)),
                ('audio_seconds', models.DecimalField(decimal_places=3, max_digits=14, null=True)),
                ('cost_cny', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('price_snapshot', models.JSONField(default=dict)),
                ('elapsed_ms', models.PositiveIntegerField(null=True)),
                ('outcome', models.CharField(blank=True, max_length=24)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.family')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_analysis.aiprovider')),
            ],
            options={
                'verbose_name': '模型调用用量',
                'verbose_name_plural': '模型调用用量',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['family', 'started_at'], name='monitoring__family__00b400_idx'), models.Index(fields=['vendor_request_id'], name='monitoring__vendor__f27dd1_idx')],
            },
        ),
    ]
