# Generated by Django 5.2.17 on 2026-09-29 03:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=150)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('token', 'Token'), ('minute', '分钟'), ('call', '次')], max_length=12)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_allowances', to='monitoring.balanceaccount')),
            ],
            options={
                'verbose_name': '模型剩余额度',
                'verbose_name_plural': '模型剩余额度',
                'constraints': [models.UniqueConstraint(fields=('account', 'model_name'), name='monitor_unique_model_allowance')],
            },
        ),
    ]
