# Generated by Django 5.2.17 on 2026-10-07 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0010_two_level_asset_dictionary'),
        ('monitoring', '0002_modelallowance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField()),
                ('backup_sha256', models.CharField(max_length=64)),
                ('report_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('passed', '通过'), ('incomplete', '验证未完整通过')], max_length=16)),
                ('checks', models.JSONField(default=list)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.family')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.familymember')),
            ],
            options={
                'verbose_name': '隔离恢复验证记录',
                'verbose_name_plural': '隔离恢复验证记录',
                'ordering': ['-completed_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('family', 'report_sha256'), name='restore_report_per_family')],
            },
        ),
    ]
