# Generated by Django 5.2.15 on 2026-06-19 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MacroIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20, verbose_name='国家/地区')),
                ('code', models.CharField(max_length=100, verbose_name='指标代码')),
                ('name', models.CharField(max_length=200, verbose_name='指标名称')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='分类')),
                ('frequency', models.CharField(blank=True, max_length=30, verbose_name='频率')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='单位')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='数据来源')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '宏观指标',
                'verbose_name_plural': '宏观指标',
                'constraints': [models.UniqueConstraint(fields=('country', 'code'), name='unique_macro_indicator')],
            },
        ),
        migrations.CreateModel(
            name='MacroDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(verbose_name='数据日期')),
                ('value', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='数值')),
                ('revised_value', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True, verbose_name='修正值')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='macro.macroindicator', verbose_name='指标')),
            ],
            options={
                'verbose_name': '宏观数据点',
                'verbose_name_plural': '宏观数据点',
                'indexes': [models.Index(fields=['indicator', 'period_date'], name='macro_macro_indicat_04f6b8_idx')],
            },
        ),
    ]
