# Generated by Django 5.2.16 on 2026-10-04 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=80, verbose_name='采集组')),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='running', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('summary', models.JSONField(default=dict, verbose_name='统计')),
                ('error', models.CharField(blank=True, max_length=500, verbose_name='错误')),
            ],
        ),
        migrations.CreateModel(
            name='MacroSourceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30, verbose_name='来源')),
                ('group', models.CharField(max_length=80, verbose_name='采集组')),
                ('definition', models.JSONField(verbose_name='口径及字段映射')),
                ('definition_hash', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mapping', to='macro.macroindicator')),
            ],
        ),
        migrations.CreateModel(
            name='MacroObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geography', models.CharField(default='全国', max_length=50, verbose_name='地区')),
                ('period_date', models.DateField(verbose_name='统计期（期初）')),
                ('value', models.DecimalField(decimal_places=8, max_digits=24, null=True, verbose_name='数值')),
                ('release_date', models.DateField(null=True, verbose_name='官方发布日期')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('fingerprint', models.CharField(max_length=64)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='macro.macrosourcemapping')),
            ],
            options={
                'ordering': ['-period_date', 'geography'],
            },
        ),
        migrations.CreateModel(
            name='MacroObservationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('value', models.DecimalField(decimal_places=8, max_digits=24, null=True)),
                ('release_date', models.DateField(null=True)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.URLField(max_length=1000)),
                ('source_hash', models.CharField(max_length=64, verbose_name='响应校验值')),
                ('evidence', models.JSONField(verbose_name='来源字段及口径')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='macro.macroobservation')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro.macroimportrun')),
            ],
            options={
                'ordering': ['-number'],
                'constraints': [models.UniqueConstraint(fields=('observation', 'number'), name='unique_macro_revision')],
            },
        ),
        migrations.AddConstraint(
            model_name='macroobservation',
            constraint=models.UniqueConstraint(fields=('mapping', 'geography', 'period_date'), name='unique_macro_observation'),
        ),
    ]
