# Generated by Django 5.2.17 on 2026-10-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0002_macroimportrun_macrosourcemapping_macroobservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroMaintenanceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=20, verbose_name='任务')),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('interrupted', '已中断')], default='running', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('summary', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MacroOfficialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=80, verbose_name='来源')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name='官方报告')),
                ('title', models.CharField(max_length=300)),
                ('period_date', models.DateField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('summary', models.JSONField(default=dict)),
                ('checked_at', models.DateTimeField(null=True)),
                ('imported_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MacroCalendarSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=30)),
                ('source_url', models.URLField(max_length=1000)),
                ('content_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(verbose_name='已核验计划日历')),
                ('checked_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agency', 'content_hash'), name='unique_macro_calendar_snapshot')],
            },
        ),
    ]
