# Generated by Django 5.2.17 on 2026-10-05 10:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0004_correct_reviewed_pmi_seasonal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroOperationsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField()),
                ('payload', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='MacroAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=180)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('details', models.JSONField(default=dict)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-opened_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('key',), name='unique_open_macro_alert')],
            },
        ),
        migrations.CreateModel(
            name='MacroPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=300)),
                ('period_date', models.DateField()),
                ('release_date', models.DateField(null=True)),
                ('codes', models.JSONField(default=list)),
                ('source_url', models.URLField(max_length=1000)),
                ('source_hash', models.CharField(max_length=64)),
                ('evidence', models.JSONField(default=dict)),
                ('verified_at', models.DateTimeField()),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agency', 'key', 'period_date'), name='unique_macro_publication')],
            },
        ),
        migrations.CreateModel(
            name='MacroAlertRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macro.macroalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('alert', 'user'), name='unique_macro_alert_read')],
            },
        ),
    ]
