# Generated by Django 5.2.15 on 2026-06-19 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='服务商名称')),
                ('provider_type', models.CharField(max_length=50, verbose_name='服务商类型')),
                ('base_url', models.URLField(blank=True, max_length=500, verbose_name='API 地址')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='默认模型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展字段')),
            ],
            options={
                'verbose_name': 'AI 服务商',
                'verbose_name_plural': 'AI 服务商',
            },
        ),
        migrations.CreateModel(
            name='AiAnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('module', models.CharField(max_length=50, verbose_name='分析模块')),
                ('analysis_type', models.CharField(blank=True, max_length=100, verbose_name='分析类型')),
                ('scope', models.JSONField(blank=True, default=dict, verbose_name='分析范围')),
                ('prompt', models.TextField(verbose_name='提示词')),
                ('sanitized_input', models.JSONField(blank=True, default=dict, verbose_name='脱敏后的输入数据')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='family_core.family', verbose_name='所属家庭')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='family_core.familymember', verbose_name='发起成员')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='ai_analysis.aiprovider', verbose_name='AI 服务商')),
            ],
            options={
                'verbose_name': 'AI 分析请求',
                'verbose_name_plural': 'AI 分析请求',
            },
        ),
        migrations.CreateModel(
            name='AiAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_text', models.TextField(blank=True, verbose_name='分析结果')),
                ('result_json', models.JSONField(blank=True, default=dict, verbose_name='结构化结果')),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True, verbose_name='Token 用量')),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='费用估算')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='ai_analysis.aianalysisrequest', verbose_name='请求')),
            ],
            options={
                'verbose_name': 'AI 分析结果',
                'verbose_name_plural': 'AI 分析结果',
            },
        ),
        migrations.AddIndex(
            model_name='aianalysisrequest',
            index=models.Index(fields=['family', 'member', 'module', 'created_at'], name='ai_analysis_family__58c3fd_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysisrequest',
            index=models.Index(fields=['status'], name='ai_analysis_status_4c7dce_idx'),
        ),
    ]
