# Generated by Django 5.2.16 on 2026-09-09 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0007_add_deepseek_global_ai_provider'),
        ('family_core', '0008_assetcategory_code_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiFamilyOutboundAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('data_type', models.CharField(choices=[('financial', '全家财务数据')], default='financial', max_length=30, verbose_name='数据类型')),
                ('is_allowed', models.BooleanField(default=False, verbose_name='允许发送')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changed_ai_family_outbound_authorizations', to='family_core.familymember', verbose_name='最近操作成员')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_family_outbound_authorizations', to='family_core.family', verbose_name='所属家庭')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_outbound_authorizations', to='ai_analysis.aiprovider', verbose_name='服务商')),
            ],
            options={
                'verbose_name': '全局 AI 家庭外发授权',
                'verbose_name_plural': '全局 AI 家庭外发授权',
                'constraints': [models.UniqueConstraint(fields=('family', 'provider', 'data_type'), name='unique_ai_family_outbound_authorization'), models.CheckConstraint(condition=models.Q(('data_type', 'financial')), name='ai_family_outbound_financial_only')],
            },
        ),
    ]
