# Generated by Django 5.2.15 on 2026-07-30 13:01

import django.db.models.deletion
import django.utils.timezone
import knowledge.models
import knowledge.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('external_id', models.CharField(max_length=500, verbose_name='外部文档 ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('author', models.CharField(blank=True, max_length=300, verbose_name='作者')),
                ('section_name', models.CharField(blank=True, max_length=300, verbose_name='分区')),
                ('hierarchy', models.JSONField(blank=True, default=dict, verbose_name='来源层级')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='原始链接')),
                ('visibility', models.CharField(choices=[('private', '仅自己'), ('family', '家庭可见')], default='family', max_length=20, verbose_name='可见范围')),
                ('sync_status', models.CharField(choices=[('available', '来源可用'), ('error', '同步异常'), ('source_deleted', '来源已删除或不可访问')], default='available', max_length=30, verbose_name='同步状态')),
                ('curation_status', models.CharField(choices=[('inbox', '收件箱'), ('normalized', '已规范化'), ('pending_ai', '待 AI 处理'), ('pending_review', '待人工确认'), ('confirmed', '已确认'), ('ignored', '已忽略'), ('archived', '已归档')], default='inbox', max_length=30, verbose_name='整理状态')),
                ('content_created_at', models.DateTimeField(blank=True, null=True, verbose_name='内容创建时间')),
                ('content_modified_at', models.DateTimeField(blank=True, null=True, verbose_name='内容修改时间')),
                ('source_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='来源删除识别时间')),
                ('confirmed_summary', models.TextField(blank=True, verbose_name='已确认摘要')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='已确认分类')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='已确认标签')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='family_core.family', verbose_name='所属家庭')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to='family_core.familymember', verbose_name='资料所有者')),
            ],
            options={
                'verbose_name': '知识文档',
                'verbose_name_plural': '知识文档',
                'ordering': ['-content_modified_at', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(verbose_name='版本号')),
                ('content_hash', models.CharField(max_length=64, verbose_name='内容哈希')),
                ('raw_file', models.FileField(max_length=1000, storage=knowledge.storage.ProtectedKnowledgeStorage(), upload_to=knowledge.models.revision_raw_upload_to, verbose_name='原始内容')),
                ('normalized_html', models.TextField(blank=True, verbose_name='安全展示正文')),
                ('plain_text', models.TextField(blank=True, verbose_name='纯文本正文')),
                ('converter_version', models.CharField(default='onenote-html-v1', max_length=50, verbose_name='转换器版本')),
                ('source_modified_at', models.DateTimeField(blank=True, null=True, verbose_name='来源修改时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='同步时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='knowledge.knowledgedocument', verbose_name='知识文档')),
            ],
            options={
                'verbose_name': '知识文档版本',
                'verbose_name_plural': '知识文档版本',
                'ordering': ['-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_type', models.CharField(choices=[('summary', '摘要建议'), ('tags', '标签建议'), ('category', '分类建议')], max_length=30, verbose_name='建议类型')),
                ('suggested_value', models.JSONField(default=dict, verbose_name='AI 建议')),
                ('human_value', models.JSONField(blank=True, default=dict, verbose_name='人工确认值')),
                ('model_name', models.CharField(max_length=200, verbose_name='模型')),
                ('prompt_version', models.CharField(max_length=50, verbose_name='提示词版本')),
                ('content_hash', models.CharField(max_length=64, verbose_name='输入内容哈希')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('stale', '内容已更新')], default='pending', max_length=20, verbose_name='确认状态')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_knowledge_proposals', to='family_core.familymember', verbose_name='确认人')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='knowledge.knowledgedocument', verbose_name='知识文档')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='knowledge.knowledgerevision', verbose_name='对应内容版本')),
            ],
            options={
                'verbose_name': '知识整理建议',
                'verbose_name_plural': '知识整理建议',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.knowledgerevision', verbose_name='当前内容版本'),
        ),
        migrations.CreateModel(
            name='KnowledgeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=500, verbose_name='外部资源 ID')),
                ('original_name', models.CharField(blank=True, max_length=300, verbose_name='原始文件名')),
                ('mime_type', models.CharField(max_length=200, verbose_name='MIME 类型')),
                ('byte_size', models.PositiveBigIntegerField(verbose_name='文件大小')),
                ('content_hash', models.CharField(max_length=64, verbose_name='文件哈希')),
                ('is_image', models.BooleanField(default=False, verbose_name='是否为正文图片')),
                ('file', models.FileField(max_length=1000, storage=knowledge.storage.ProtectedKnowledgeStorage(), upload_to=knowledge.models.asset_upload_to, verbose_name='受保护文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='保存时间')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='knowledge.knowledgerevision', verbose_name='内容版本')),
            ],
            options={
                'verbose_name': '知识附件',
                'verbose_name_plural': '知识附件',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSearchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('item_kind', models.CharField(choices=[('document', '知识文档'), ('investment_note', '随手记')], max_length=30, verbose_name='条目类型')),
                ('object_id', models.CharField(max_length=100, verbose_name='原业务对象 ID')),
                ('visibility', models.CharField(choices=[('private', '仅自己'), ('family', '家庭可见')], max_length=20, verbose_name='可见范围')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('body', models.TextField(blank=True, verbose_name='正文索引')),
                ('summary', models.TextField(blank=True, verbose_name='摘要索引')),
                ('source_kind', models.CharField(max_length=30, verbose_name='来源类型')),
                ('source_name', models.CharField(max_length=300, verbose_name='来源名称')),
                ('author_name', models.CharField(blank=True, max_length=200, verbose_name='作者')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='分类')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('tags_text', models.TextField(blank=True, verbose_name='标签检索文本')),
                ('searchable_text', models.TextField(blank=True, verbose_name='统一检索文本')),
                ('curation_status', models.CharField(blank=True, max_length=30, verbose_name='整理状态')),
                ('content_time', models.DateTimeField(blank=True, null=True, verbose_name='内容时间')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_entry', to='knowledge.knowledgedocument', verbose_name='知识文档')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_search_entries', to='family_core.family', verbose_name='所属家庭')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_search_entries', to='family_core.familymember', verbose_name='资料所有者')),
            ],
            options={
                'verbose_name': '知识搜索投影',
                'verbose_name_plural': '知识搜索投影',
                'ordering': ['-content_time', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('key', models.CharField(max_length=500, verbose_name='稳定来源键')),
                ('kind', models.CharField(choices=[('onenote', 'OneNote'), ('internal_notes', '随手记')], max_length=30, verbose_name='来源类型')),
                ('name', models.CharField(max_length=300, verbose_name='来源名称')),
                ('external_id', models.CharField(blank=True, max_length=500, verbose_name='外部来源 ID')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='来源链接')),
                ('visibility', models.CharField(choices=[('private', '仅自己'), ('family', '家庭可见')], default='family', max_length=20, verbose_name='默认可见范围')),
                ('allow_cloud_ai', models.BooleanField(default=False, verbose_name='允许发送正文给已配置的云端 AI')),
                ('status', models.CharField(choices=[('active', '正常'), ('error', '需要处理'), ('disconnected', '连接已断开')], default='active', max_length=20, verbose_name='来源状态')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='非敏感配置')),
                ('sync_cursor', models.JSONField(blank=True, default=dict, verbose_name='同步游标')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最近同步时间')),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='最近完整对账时间')),
                ('last_error', models.TextField(blank=True, verbose_name='最近错误摘要')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='family_core.family', verbose_name='所属家庭')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_sources', to='family_core.familymember', verbose_name='来源所有者')),
            ],
            options={
                'verbose_name': '知识来源',
                'verbose_name_plural': '知识来源',
                'ordering': ['kind', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job_type', models.CharField(choices=[('sync_source', '同步来源'), ('generate_proposals', '生成 AI 整理建议'), ('rebuild_search', '重建搜索索引')], max_length=40, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '运行中'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败'), ('source_unavailable', '来源不可访问'), ('cancel_requested', '正在取消'), ('cancelled', '已取消')], default='pending', max_length=30, verbose_name='任务状态')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='任务参数')),
                ('cursor', models.JSONField(blank=True, default=dict, verbose_name='任务游标')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='总项数')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='新增数')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='更新数')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='跳过数')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失败数')),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='计划时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='最近心跳')),
                ('error_message', models.TextField(blank=True, verbose_name='错误摘要')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='任务结果')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_jobs', to='family_core.family', verbose_name='所属家庭')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_jobs', to='family_core.familymember', verbose_name='发起成员')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='knowledge.knowledgesource', verbose_name='知识来源')),
            ],
            options={
                'verbose_name': '知识后台任务',
                'verbose_name_plural': '知识后台任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='knowledge.knowledgesource', verbose_name='知识来源'),
        ),
        migrations.CreateModel(
            name='SourceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.CharField(choices=[('microsoft', 'Microsoft')], default='microsoft', max_length=30, verbose_name='服务商')),
                ('external_account_id', models.CharField(blank=True, max_length=255, verbose_name='外部账户 ID')),
                ('account_display_name', models.CharField(blank=True, max_length=200, verbose_name='账户显示名称')),
                ('account_email', models.CharField(blank=True, max_length=320, verbose_name='账户邮箱')),
                ('encrypted_token_cache', models.TextField(blank=True, editable=False, verbose_name='加密令牌缓存')),
                ('granted_scopes', models.JSONField(blank=True, default=list, verbose_name='已授权范围')),
                ('available_notebooks', models.JSONField(blank=True, default=list, verbose_name='可选笔记本缓存')),
                ('status', models.CharField(choices=[('active', '正常'), ('error', '需要处理'), ('disconnected', '已断开')], default='disconnected', max_length=20, verbose_name='连接状态')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最近使用时间')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='最近成功时间')),
                ('last_error', models.TextField(blank=True, verbose_name='最近错误摘要')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_connections', to='family_core.family', verbose_name='所属家庭')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_connections', to='family_core.familymember', verbose_name='授权成员')),
            ],
            options={
                'verbose_name': '知识来源账户连接',
                'verbose_name_plural': '知识来源账户连接',
            },
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='knowledge.sourceconnection', verbose_name='账户连接'),
        ),
        migrations.CreateModel(
            name='KnowledgeJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=500, verbose_name='外部项目 ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='项目标题')),
                ('status', models.CharField(choices=[('success', '新增'), ('updated', '更新'), ('skipped', '跳过'), ('failed', '失败')], max_length=20, verbose_name='处理状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='knowledge.knowledgejob', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '知识任务项目',
                'verbose_name_plural': '知识任务项目',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['job', 'status'], name='knowledge_k_job_id_2cb7c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'external_id'), name='unique_knowledge_job_item')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgerevision',
            index=models.Index(fields=['document', 'created_at'], name='knowledge_k_documen_af79fa_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgerevision',
            index=models.Index(fields=['content_hash'], name='knowledge_k_content_321365_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgerevision',
            constraint=models.UniqueConstraint(fields=('document', 'revision_number'), name='unique_knowledge_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='knowledgerevision',
            constraint=models.UniqueConstraint(fields=('document', 'content_hash'), name='unique_knowledge_revision_content_hash'),
        ),
        migrations.AddIndex(
            model_name='knowledgeproposal',
            index=models.Index(fields=['document', 'status'], name='knowledge_k_documen_cb8683_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeproposal',
            index=models.Index(fields=['revision', 'status'], name='knowledge_k_revisio_5490c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeproposal',
            constraint=models.UniqueConstraint(fields=('revision', 'proposal_type', 'prompt_version'), name='unique_knowledge_proposal_per_revision_type_prompt'),
        ),
        migrations.AddIndex(
            model_name='knowledgeasset',
            index=models.Index(fields=['revision', 'is_image'], name='knowledge_k_revisio_cc770f_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeasset',
            index=models.Index(fields=['content_hash'], name='knowledge_k_content_dc09aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeasset',
            constraint=models.UniqueConstraint(fields=('revision', 'external_id'), name='unique_knowledge_asset_per_revision'),
        ),
        migrations.AddIndex(
            model_name='knowledgesearchentry',
            index=models.Index(fields=['family', 'visibility', 'owner'], name='knowledge_k_family__1f4a39_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesearchentry',
            index=models.Index(fields=['family', 'source_kind', 'content_time'], name='knowledge_k_family__788b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesearchentry',
            index=models.Index(fields=['family', 'curation_status'], name='knowledge_k_family__626475_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesearchentry',
            constraint=models.UniqueConstraint(fields=('family', 'item_kind', 'object_id'), name='unique_knowledge_search_projection'),
        ),
        migrations.AddIndex(
            model_name='knowledgejob',
            index=models.Index(fields=['status', 'scheduled_at'], name='knowledge_k_status_44198c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgejob',
            index=models.Index(fields=['family', 'created_at'], name='knowledge_k_family__5ae3be_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgejob',
            index=models.Index(fields=['source', 'job_type', 'created_at'], name='knowledge_k_source__022701_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running', 'cancel_requested'])), fields=('source', 'job_type'), name='unique_active_knowledge_job_per_source_type'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['family', 'visibility', 'owner'], name='knowledge_k_family__59f034_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['source', 'sync_status'], name='knowledge_k_source__313c37_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['family', 'curation_status'], name='knowledge_k_family__4b108c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['content_modified_at'], name='knowledge_k_content_e562c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_knowledge_document_per_source'),
        ),
        migrations.AddIndex(
            model_name='sourceconnection',
            index=models.Index(fields=['family', 'provider', 'status'], name='knowledge_s_family__a57936_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceconnection',
            index=models.Index(fields=['member', 'provider'], name='knowledge_s_member__8f28de_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourceconnection',
            constraint=models.UniqueConstraint(fields=('family', 'member', 'provider'), name='unique_knowledge_connection_per_member_provider'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['family', 'kind', 'status'], name='knowledge_k_family__0636d0_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['owner', 'kind'], name='knowledge_k_owner_i_9ffe20_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.UniqueConstraint(fields=('family', 'key'), name='unique_knowledge_source_key_per_family'),
        ),
    ]
