# Generated by Django 5.2.15 on 2026-07-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_index_existing_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgesearchentry',
            name='curation_status',
            field=models.CharField(blank=True, choices=[('inbox', '收件箱'), ('normalized', '已规范化'), ('pending_ai', '待 AI 处理'), ('pending_review', '待人工确认'), ('confirmed', '已确认'), ('ignored', '已忽略'), ('archived', '已归档')], max_length=30, verbose_name='整理状态'),
        ),
    ]
