# Generated by Django 5.2.16 on 2026-08-08 02:09

import django.db.models.deletion
import knowledge.models
import knowledge.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('knowledge', '0005_knowledge_status_and_opt_in_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeasset',
            name='source_path',
            field=models.CharField(blank=True, max_length=1000, verbose_name='原始相对路径'),
        ),
        migrations.AddField(
            model_name='knowledgerevision',
            name='normalized_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='规范正文哈希'),
        ),
        migrations.AlterField(
            model_name='knowledgejob',
            name='job_type',
            field=models.CharField(choices=[('sync_source', '同步来源'), ('generate_proposals', '生成 AI 整理建议'), ('rebuild_search', '重建搜索索引'), ('preview_import', '检查导入资料'), ('import_batch', '执行资料导入'), ('rollback_import', '回滚导入批次')], max_length=40, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='kind',
            field=models.CharField(choices=[('onenote', 'OneNote'), ('internal_notes', '随手记'), ('html_import', 'HTML 历史资料'), ('markdown_import', 'Markdown 历史资料')], max_length=30, verbose_name='来源类型'),
        ),
        migrations.CreateModel(
            name='KnowledgeImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='批次标识')),
                ('import_format', models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown')], max_length=20, verbose_name='导入格式')),
                ('source_filename', models.CharField(max_length=300, verbose_name='上传文件名')),
                ('source_sha256', models.CharField(max_length=64, verbose_name='上传包校验值')),
                ('package_file', models.FileField(max_length=1000, storage=knowledge.storage.ProtectedKnowledgeStorage(), upload_to=knowledge.models.import_package_upload_to, verbose_name='受保护的原始导入包')),
                ('visibility', models.CharField(choices=[('private', '仅自己'), ('family', '家庭可见')], default='family', max_length=20, verbose_name='默认可见范围')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='批次默认分类')),
                ('status', models.CharField(choices=[('uploaded', '等待格式检查'), ('previewing', '正在格式检查'), ('preview_ready', '等待确认导入'), ('importing', '正在导入'), ('completed', '导入完成'), ('partial', '部分完成'), ('failed', '需要处理'), ('rolling_back', '正在回滚'), ('rolled_back', '已回滚')], default='uploaded', max_length=30, verbose_name='批次状态')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='文件数')),
                ('new_count', models.PositiveIntegerField(default=0, verbose_name='预计新增')),
                ('update_count', models.PositiveIntegerField(default=0, verbose_name='预计更新')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='预计跳过')),
                ('duplicate_count', models.PositiveIntegerField(default=0, verbose_name='强重复')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='错误数')),
                ('asset_count', models.PositiveIntegerField(default=0, verbose_name='图片数')),
                ('estimated_bytes', models.PositiveBigIntegerField(default=0, verbose_name='预计保存字节')),
                ('previewed_at', models.DateTimeField(blank=True, null=True, verbose_name='预览完成时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认导入时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='导入完成时间')),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True, verbose_name='回滚完成时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误摘要')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='批次结果')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_import_batches', to='family_core.family', verbose_name='所属家庭')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_import_batches', to='family_core.familymember', verbose_name='发起成员')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='knowledge.knowledgesource', verbose_name='知识来源')),
            ],
            options={
                'verbose_name': '知识导入批次',
                'verbose_name_plural': '知识导入批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=1000, verbose_name='原始相对路径')),
                ('external_id', models.CharField(blank=True, max_length=500, verbose_name='稳定文档 ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='标题')),
                ('author', models.CharField(blank=True, max_length=300, verbose_name='作者')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='原文链接')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('directory_path', models.CharField(blank=True, max_length=1000, verbose_name='原始目录')),
                ('raw_sha256', models.CharField(blank=True, max_length=64, verbose_name='原文件哈希')),
                ('normalized_sha256', models.CharField(blank=True, max_length=64, verbose_name='规范正文哈希')),
                ('action', models.CharField(choices=[('new', '新增'), ('update', '更新'), ('unchanged', '内容未变化'), ('duplicate', '强重复'), ('error', '无法导入')], default='error', max_length=20, verbose_name='预览结论')),
                ('status', models.CharField(choices=[('previewed', '已检查'), ('imported', '已导入'), ('skipped', '已跳过'), ('failed', '失败'), ('rolled_back', '已回滚')], default='previewed', max_length=20, verbose_name='处理状态')),
                ('asset_count', models.PositiveIntegerField(default=0, verbose_name='图片数')),
                ('asset_bytes', models.PositiveBigIntegerField(default=0, verbose_name='图片字节')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='格式警告')),
                ('error_message', models.TextField(blank=True, verbose_name='错误')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='解析详情')),
                ('previous_state', models.JSONField(blank=True, default=dict, verbose_name='导入前元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='knowledge.knowledgeimportbatch', verbose_name='导入批次')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_items', to='knowledge.knowledgedocument', verbose_name='导入后的文档')),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_import_items', to='knowledge.knowledgerevision', verbose_name='导入前版本')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_items', to='knowledge.knowledgerevision', verbose_name='导入产生的版本')),
            ],
            options={
                'verbose_name': '知识导入项目',
                'verbose_name_plural': '知识导入项目',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeimportbatch',
            index=models.Index(fields=['family', 'status', 'created_at'], name='knowledge_k_family__5d68a3_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeimportbatch',
            index=models.Index(fields=['source', 'created_at'], name='knowledge_k_source__bec477_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeimportbatch',
            index=models.Index(fields=['source_sha256'], name='knowledge_k_source__9e958a_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeimportitem',
            index=models.Index(fields=['batch', 'action'], name='knowledge_k_batch_i_0076cb_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeimportitem',
            index=models.Index(fields=['batch', 'status'], name='knowledge_k_batch_i_20486b_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeimportitem',
            index=models.Index(fields=['external_id'], name='knowledge_k_externa_6ce665_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeimportitem',
            index=models.Index(fields=['normalized_sha256'], name='knowledge_k_normali_f47247_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeimportitem',
            constraint=models.UniqueConstraint(fields=('batch', 'relative_path'), name='unique_knowledge_import_item_path'),
        ),
    ]
