# Generated by Django 5.2.16 on 2026-08-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('knowledge', '0006_knowledgeasset_source_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='library_tier',
            field=models.CharField(choices=[('knowledge', '精选知识'), ('archive', '资料库历史归档')], db_index=True, default='knowledge', max_length=20, verbose_name='资料库层级'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['family', 'library_tier', 'knowledge_status'], name='knowledge_k_family__2436e5_idx'),
        ),
    ]
