# Generated by Django 5.2.16 on 2026-08-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_taxonomy_and_proposal_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgesource',
            name='kind',
            field=models.CharField(choices=[('onenote', 'OneNote'), ('internal_notes', '随手记'), ('html_import', 'HTML 历史资料'), ('markdown_import', 'Markdown 历史资料'), ('intelligence', 'AI 情报归档')], max_length=30, verbose_name='来源类型'),
        ),
    ]
