# Generated by Django 5.2.16 on 2026-08-23 08:59

import django.db.models.deletion
import knowledge.models
import knowledge.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('knowledge', '0011_alter_knowledgesource_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgesearchentry',
            name='item_kind',
            field=models.CharField(choices=[('document', '知识文档'), ('investment_note', '随手记'), ('artifact', 'AI 专题成果')], max_length=30, verbose_name='条目类型'),
        ),
        migrations.CreateModel(
            name='KnowledgeArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('person_name', models.CharField(max_length=300, verbose_name='关联人物')),
                ('normalized_person_name', models.CharField(max_length=300, verbose_name='规范人物名')),
                ('artifact_type', models.CharField(choices=[('manual', '专题知识手册'), ('mind_map', '交互式知识体系图')], max_length=30, verbose_name='成果类型')),
                ('title', models.CharField(max_length=500, verbose_name='成果标题')),
                ('description', models.TextField(blank=True, verbose_name='成果说明')),
                ('visibility', models.CharField(choices=[('private', '仅自己'), ('family', '家庭可见')], default='family', max_length=20, verbose_name='可见范围')),
                ('status', models.CharField(choices=[('pending', 'AI 生成 · 待人工确认'), ('confirmed', '已人工确认'), ('superseded', '已被新成果替代')], default='pending', max_length=20, verbose_name='确认状态')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_knowledge_artifacts', to='family_core.familymember', verbose_name='确认人')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_artifacts', to='family_core.family', verbose_name='所属家庭')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_artifacts', to='family_core.familymember', verbose_name='成果所有者')),
            ],
            options={
                'verbose_name': 'AI 专题成果',
                'verbose_name_plural': 'AI 专题成果',
                'ordering': ['person_name', 'artifact_type', 'title', 'id'],
            },
        ),
        migrations.AddField(
            model_name='knowledgesearchentry',
            name='artifact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_entry', to='knowledge.knowledgeartifact', verbose_name='AI 专题成果'),
        ),
        migrations.CreateModel(
            name='KnowledgeArtifactVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='版本号')),
                ('original_file', models.FileField(max_length=1000, storage=knowledge.storage.ProtectedKnowledgeStorage(), upload_to=knowledge.models.artifact_original_upload_to, verbose_name='AI 生成原文件')),
                ('rendered_file', models.FileField(blank=True, max_length=1000, storage=knowledge.storage.ProtectedKnowledgeStorage(), upload_to=knowledge.models.artifact_rendered_upload_to, verbose_name='安全展示版本')),
                ('original_name', models.CharField(max_length=300, verbose_name='原始文件名')),
                ('content_hash', models.CharField(max_length=64, verbose_name='原文件 SHA-256')),
                ('byte_size', models.PositiveBigIntegerField(verbose_name='原文件大小')),
                ('plain_text', models.TextField(blank=True, verbose_name='可搜索文本')),
                ('generator_name', models.CharField(blank=True, max_length=100, verbose_name='生成工具')),
                ('model_name', models.CharField(blank=True, max_length=200, verbose_name='模型')),
                ('prompt_version', models.CharField(blank=True, max_length=100, verbose_name='提示词版本')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='生成时间')),
                ('source_article_count', models.PositiveIntegerField(default=0, verbose_name='声明来源文章数')),
                ('source_cutoff_date', models.DateField(blank=True, null=True, verbose_name='来源截止日期')),
                ('source_snapshot', models.JSONField(blank=True, default=list, verbose_name='来源版本快照')),
                ('reference_count', models.PositiveIntegerField(default=0, verbose_name='引用数')),
                ('matched_reference_count', models.PositiveIntegerField(default=0, verbose_name='已匹配引用数')),
                ('ambiguous_reference_count', models.PositiveIntegerField(default=0, verbose_name='重复待核对引用数')),
                ('unmatched_reference_count', models.PositiveIntegerField(default=0, verbose_name='未匹配引用数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='保存时间')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.knowledgeartifact', verbose_name='专题成果')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_knowledge_artifact_versions', to='family_core.familymember', verbose_name='上传人')),
            ],
            options={
                'verbose_name': 'AI 专题成果版本',
                'verbose_name_plural': 'AI 专题成果版本',
                'ordering': ['-version_number', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArtifactEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_key', models.CharField(max_length=64, verbose_name='稳定引用键')),
                ('citation_text', models.CharField(max_length=1000, verbose_name='引用原文')),
                ('citation_title', models.CharField(max_length=500, verbose_name='引用文章标题')),
                ('citation_date', models.DateField(blank=True, null=True, verbose_name='引用文章日期')),
                ('status', models.CharField(choices=[('matched', '已映射原文'), ('ambiguous', '存在重复候选'), ('unmatched', '未找到原文')], max_length=20, verbose_name='映射状态')),
                ('match_method', models.CharField(blank=True, max_length=50, verbose_name='匹配方式')),
                ('candidate_document_ids', models.JSONField(blank=True, default=list, verbose_name='候选文档 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立时间')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_evidence_links', to='knowledge.knowledgedocument', verbose_name='映射文档')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_evidence_links', to='knowledge.knowledgerevision', verbose_name='映射内容版本')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='knowledge.knowledgeartifactversion', verbose_name='成果版本')),
            ],
            options={
                'verbose_name': '专题成果引用证据',
                'verbose_name_plural': '专题成果引用证据',
                'ordering': ['citation_date', 'citation_title', 'id'],
            },
        ),
        migrations.AddField(
            model_name='knowledgeartifact',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.knowledgeartifactversion', verbose_name='当前成果版本'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeartifactversion',
            constraint=models.UniqueConstraint(fields=('artifact', 'version_number'), name='unique_knowledge_artifact_version_number'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeartifactversion',
            constraint=models.UniqueConstraint(fields=('artifact', 'content_hash'), name='unique_knowledge_artifact_content_hash'),
        ),
        migrations.AddIndex(
            model_name='knowledgeartifactevidence',
            index=models.Index(fields=['version', 'status'], name='knowledge_k_version_f6dc2b_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeartifactevidence',
            index=models.Index(fields=['document', 'revision'], name='knowledge_k_documen_690053_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeartifactevidence',
            constraint=models.UniqueConstraint(fields=('version', 'reference_key'), name='unique_knowledge_artifact_reference'),
        ),
        migrations.AddIndex(
            model_name='knowledgeartifact',
            index=models.Index(fields=['family', 'visibility', 'owner'], name='knowledge_k_family__8a8916_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeartifact',
            index=models.Index(fields=['family', 'normalized_person_name', 'status'], name='knowledge_k_family__1deef6_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeartifact',
            constraint=models.UniqueConstraint(fields=('family', 'normalized_person_name', 'artifact_type'), name='unique_knowledge_artifact_type_per_person'),
        ),
    ]
