# Generated by Django 5.2.16 on 2026-09-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0012_alter_knowledgesearchentry_item_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgesource',
            name='kind',
            field=models.CharField(choices=[('onenote', 'OneNote'), ('internal_notes', '随手记'), ('html_import', 'HTML 历史资料'), ('markdown_import', 'Markdown 历史资料'), ('intelligence', 'AI 情报归档'), ('reading', '阅读成果')], max_length=30, verbose_name='来源类型'),
        ),
    ]
