# Generated by Django 5.2.17 on 2026-10-02 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('knowledge', '0013_alter_knowledgesource_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgejob',
            name='job_type',
            field=models.CharField(choices=[('sync_source', '同步来源'), ('generate_proposals', '生成 AI 整理建议'), ('rebuild_search', '重建搜索索引'), ('preview_import', '检查导入资料'), ('import_batch', '执行资料导入'), ('rollback_import', '回滚导入批次'), ('capture_web', '保存网页收藏')], max_length=40, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='kind',
            field=models.CharField(choices=[('onenote', 'OneNote'), ('internal_notes', '随手记'), ('html_import', 'HTML 历史资料'), ('markdown_import', 'Markdown 历史资料'), ('intelligence', 'AI 情报归档'), ('reading', '阅读成果'), ('web_capture', '网页收藏')], max_length=30, verbose_name='来源类型'),
        ),
        migrations.CreateModel(
            name='KnowledgeWebCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('url', models.URLField(max_length=1000, verbose_name='网页链接')),
                ('url_hash', models.CharField(max_length=64)),
                ('visibility', models.CharField(choices=[('private', '仅自己'), ('family', '家庭可见')], default='private', max_length=20, verbose_name='可见范围')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='收藏备注')),
                ('organize_with_ai', models.BooleanField(default=True, verbose_name='生成 AI 整理建议')),
                ('stage', models.CharField(choices=[('queued', '等待保存'), ('capture', '抓取正文'), ('images', '归档图片'), ('ai', '生成整理建议'), ('done', '已保存'), ('failed', '需要重试')], default='queued', max_length=30, verbose_name='当前步骤')),
                ('image_failures', models.JSONField(blank=True, default=list, verbose_name='未保存图片')),
                ('error_message', models.TextField(blank=True, verbose_name='错误说明')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_capture', to='knowledge.knowledgedocument')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_core.family')),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_captures', to='knowledge.knowledgejob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_core.familymember')),
            ],
            options={
                'verbose_name': '网页收藏',
                'verbose_name_plural': '网页收藏',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'url_hash'), name='unique_web_capture_owner_url')],
            },
        ),
    ]
