# Generated by Django 5.2.17 on 2026-10-05 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('knowledge', '0014_alter_knowledgejob_job_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeFileCleanup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('files', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', '等待清理'), ('failed', '清理未完成'), ('success', '清理完成')], default='pending', max_length=20)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '资料文件清理回执',
                'verbose_name_plural': '资料文件清理回执',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('trash', '移入回收站'), ('restore', '恢复资料'), ('unfeature', '移出精选'), ('purge', '彻底删除内容'), ('versions', '清理旧版本')], max_length=30)),
                ('revision_numbers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '资料管理记录',
                'verbose_name_plural': '资料管理记录',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='knowledgerevision',
            name='unique_knowledge_revision_content_hash',
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='内容彻底删除时间'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='移入回收站时间'),
        ),
        migrations.AddField(
            model_name='knowledgerevision',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='内容清理时间'),
        ),
        migrations.AddConstraint(
            model_name='knowledgerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('purged_at__isnull', True)), fields=('document', 'content_hash'), name='unique_knowledge_revision_content_hash'),
        ),
        migrations.AddField(
            model_name='knowledgefilecleanup',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_cleanups', to='knowledge.knowledgedocument'),
        ),
        migrations.AddField(
            model_name='knowledgelifecycleevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='family_core.familymember'),
        ),
        migrations.AddField(
            model_name='knowledgelifecycleevent',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='knowledge.knowledgedocument'),
        ),
    ]
