# Generated by Django 5.2.16 on 2026-08-30 07:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import option_wheel.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('portfolio', '0027_watchlistgroup_watchlistitem_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelBrokerAccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_kind', models.CharField(choices=[('manual_file', '手工文件'), ('zhifu_readonly', '致富只读'), ('ibkr_readonly', 'IBKR 只读')], max_length=30, verbose_name='来源类型')),
                ('source_reference', models.CharField(blank=True, max_length=200, verbose_name='来源引用')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='币种')),
                ('settled_cash', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True, verbose_name='已结算现金')),
                ('unsettled_cash', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True, verbose_name='未结算现金')),
                ('nav', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True, verbose_name='净值')),
                ('reserved_cash', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True, verbose_name='预留现金')),
                ('margin_loan_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True, verbose_name='保证金贷款余额')),
                ('uses_margin', models.BooleanField(blank=True, default=None, null=True, verbose_name='使用保证金')),
                ('positions_summary', models.JSONField(blank=True, null=True, verbose_name='持仓摘要')),
                ('open_obligations', models.JSONField(blank=True, null=True, verbose_name='未了义务')),
                ('source_as_of', models.DateTimeField(verbose_name='来源时点')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='获取时间')),
                ('data_status', models.CharField(choices=[('complete', '完整'), ('partial', '部分'), ('invalid', '无效')], default='partial', max_length=20, verbose_name='数据状态')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_broker_snapshots', to='portfolio.investmentaccount', verbose_name='投资账户')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_broker_snapshots', to='family_core.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '券商账户快照',
                'verbose_name_plural': '券商账户快照',
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
            bases=(option_wheel.models.AppendOnlyEvidenceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WheelMarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='行情来源')),
                ('provider_symbol', models.CharField(blank=True, max_length=100, verbose_name='行情源代码')),
                ('last_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='最新价')),
                ('source_as_of', models.DateTimeField(verbose_name='来源时点')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='获取时间')),
                ('market_session', models.CharField(blank=True, max_length=50, verbose_name='市场会话')),
                ('regular_session_verified', models.BooleanField(default=False, verbose_name='正常交易时段已核验')),
                ('calendar_reference', models.CharField(blank=True, max_length=100, verbose_name='交易日历证据')),
                ('delay_status', models.CharField(choices=[('real_time', '实时'), ('delayed', '延迟'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='延迟状态')),
                ('freshness_status', models.CharField(choices=[('fresh', '新鲜'), ('stale', '过期'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='新鲜度')),
                ('data_quality', models.CharField(choices=[('complete', '完整'), ('partial', '部分'), ('invalid', '无效')], default='partial', max_length=20, verbose_name='数据质量')),
                ('sanitized_metadata', models.JSONField(blank=True, default=dict, verbose_name='脱敏元数据')),
                ('underlying', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_market_snapshots', to='portfolio.security', verbose_name='正股标的')),
            ],
            options={
                'verbose_name': '轮动行情快照',
                'verbose_name_plural': '轮动行情快照',
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
            bases=(option_wheel.models.AppendOnlyEvidenceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WheelDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('decision_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='决策时间')),
                ('input_fingerprint', models.CharField(max_length=64, verbose_name='输入指纹')),
                ('ruleset_version', models.CharField(default='m1-v1', max_length=30, verbose_name='规则集版本')),
                ('event_status', models.CharField(choices=[('clear', '通过'), ('blocked', '阻断'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='事件状态')),
                ('technical_status', models.CharField(choices=[('complete', '完整'), ('partial', '部分'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='技术状态')),
                ('execution_gate_open', models.BooleanField(default=False, verbose_name='执行门禁已打开')),
                ('overall_status', models.CharField(choices=[('investigation', '调查中'), ('blocked', '阻断'), ('executable', '可执行')], default='investigation', max_length=20, verbose_name='总体状态')),
                ('blockers', models.JSONField(blank=True, default=list, verbose_name='阻断项')),
                ('frozen_input', models.JSONField(blank=True, default=dict, verbose_name='冻结输入')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_decisions', to='portfolio.investmentaccount', verbose_name='投资账户')),
                ('account_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='option_wheel.wheelbrokeraccountsnapshot', verbose_name='账户快照')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_decisions', to='family_core.family', verbose_name='所属家庭')),
                ('underlying', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_decisions', to='portfolio.security', verbose_name='正股标的')),
                ('market_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='option_wheel.wheelmarketsnapshot', verbose_name='行情快照')),
            ],
            options={
                'verbose_name': '轮动决策',
                'verbose_name_plural': '轮动决策',
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
            bases=(option_wheel.models.AppendOnlyEvidenceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WheelOptionQuoteSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='行情来源')),
                ('provider_contract_code', models.CharField(max_length=100, verbose_name='合约代码')),
                ('currency', models.CharField(blank=True, max_length=10, verbose_name='报价币种')),
                ('option_type', models.CharField(choices=[('put', '看跌'), ('call', '看涨')], max_length=10, verbose_name='期权类型')),
                ('expiration', models.DateField(verbose_name='到期日')),
                ('strike', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='行权价')),
                ('standard_status', models.CharField(choices=[('standard', '标准'), ('non_standard', '非标准'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='标准状态')),
                ('is_adjusted', models.BooleanField(blank=True, default=None, null=True, verbose_name='是否调整')),
                ('index_option_type', models.CharField(blank=True, max_length=30, verbose_name='指数期权类型')),
                ('underlying_asset_type', models.CharField(blank=True, max_length=30, verbose_name='标的资产类型')),
                ('exercise_style', models.CharField(blank=True, max_length=20, verbose_name='行权方式')),
                ('settlement_mode', models.CharField(blank=True, max_length=30, verbose_name='结算方式')),
                ('settlement_evidence', models.CharField(choices=[('provider_physical', '券商实物'), ('occ_standard_equity', 'OCC 标准'), ('unknown', '未知')], default='unknown', max_length=30, verbose_name='结算证据')),
                ('deliverable_shares', models.PositiveIntegerField(blank=True, null=True, verbose_name='可交割股数')),
                ('contract_multiplier', models.PositiveIntegerField(blank=True, null=True, verbose_name='合约乘数')),
                ('bid', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='买价')),
                ('ask', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='卖价')),
                ('bid_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='买量')),
                ('ask_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='卖量')),
                ('last', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='最新价')),
                ('volume', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='成交量')),
                ('open_interest', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='未平仓量')),
                ('implied_volatility', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='隐含波动率')),
                ('delta', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Delta')),
                ('gamma', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Gamma')),
                ('theta', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Theta')),
                ('vega', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Vega')),
                ('rho', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Rho')),
                ('assignment_probability', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指派概率（%）')),
                ('quote_as_of', models.DateTimeField(verbose_name='报价时点')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='获取时间')),
                ('delay_status', models.CharField(choices=[('real_time', '实时'), ('delayed', '延迟'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='延迟状态')),
                ('freshness_status', models.CharField(choices=[('fresh', '新鲜'), ('stale', '过期'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='新鲜度')),
                ('data_quality', models.CharField(choices=[('complete', '完整'), ('partial', '部分'), ('invalid', '无效')], default='partial', max_length=20, verbose_name='数据质量')),
                ('sanitized_metadata', models.JSONField(blank=True, default=dict, verbose_name='脱敏元数据')),
                ('market_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='option_quotes', to='option_wheel.wheelmarketsnapshot', verbose_name='关联行情快照')),
                ('underlying', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_option_quotes', to='portfolio.security', verbose_name='正股标的')),
            ],
            options={
                'verbose_name': '期权报价快照',
                'verbose_name_plural': '期权报价快照',
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
            bases=(option_wheel.models.AppendOnlyEvidenceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WheelCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('candidate_key', models.CharField(max_length=100, verbose_name='候选键')),
                ('strategy', models.CharField(choices=[('sell_put', '卖出看跌'), ('covered_call', '备兑看涨'), ('roll', '滚动'), ('wait', '等待')], max_length=20, verbose_name='策略')),
                ('status', models.CharField(choices=[('investigation', '调查中'), ('blocked', '阻断'), ('executable', '可执行')], default='investigation', max_length=20, verbose_name='状态')),
                ('contract_count', models.PositiveIntegerField(default=1, verbose_name='合约数量')),
                ('required_cash', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True, verbose_name='所需现金')),
                ('premium_total', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True, verbose_name='权利金总额')),
                ('break_even', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='盈亏平衡价')),
                ('annualized_premium_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='年化权利金率')),
                ('assignment_probability', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='指派概率（%）')),
                ('premium_preference_match', models.BooleanField(default=False, verbose_name='权利金偏好匹配')),
                ('dte_preference_match', models.BooleanField(default=False, verbose_name='到期日偏好匹配')),
                ('exclusion_reasons', models.JSONField(blank=True, default=list, verbose_name='排除原因')),
                ('calculation_details', models.JSONField(blank=True, default=dict, verbose_name='计算详情')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='option_wheel.wheeldecision', verbose_name='决策')),
                ('option_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='option_wheel.wheeloptionquotesnapshot', verbose_name='期权报价')),
            ],
            options={
                'verbose_name': '轮动候选',
                'verbose_name_plural': '轮动候选',
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
            bases=(option_wheel.models.AppendOnlyEvidenceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WheelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('preferred_premium_min', models.DecimalField(decimal_places=4, default=Decimal('200'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='最低权利金')),
                ('preferred_premium_max', models.DecimalField(decimal_places=4, default=Decimal('400'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='最高权利金')),
                ('preferred_dte_min', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='最短到期天数')),
                ('preferred_dte_max', models.PositiveIntegerField(default=9, validators=[django.core.validators.MinValueValidator(1)], verbose_name='最长到期天数')),
                ('max_underlying_nav_ratio', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000001')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='最大标的 NAV 占比')),
                ('max_spread_ratio', models.DecimalField(decimal_places=6, default=Decimal('0.15'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='最大买卖价差比例')),
                ('min_open_interest', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='最小未平仓量')),
                ('min_volume', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='最小成交量')),
                ('account_snapshot_max_age_minutes', models.PositiveIntegerField(default=1440, validators=[django.core.validators.MinValueValidator(1)], verbose_name='账户快照最大年龄（分钟）')),
                ('quote_max_age_seconds', models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(1)], verbose_name='报价最大年龄（秒）')),
                ('ruleset_version', models.CharField(default='m1-v1', max_length=30, verbose_name='规则集版本')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_policies', to='portfolio.investmentaccount', verbose_name='投资账户')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_policies', to='family_core.family', verbose_name='所属家庭')),
                ('underlying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_policies', to='portfolio.security', verbose_name='正股标的')),
            ],
            options={
                'verbose_name': '期权轮动策略',
                'verbose_name_plural': '期权轮动策略',
            },
        ),
        migrations.AddField(
            model_name='wheeldecision',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='option_wheel.wheelpolicy', verbose_name='策略'),
        ),
        migrations.AddIndex(
            model_name='wheelbrokeraccountsnapshot',
            index=models.Index(fields=['family', 'account', 'source_as_of'], name='wheel_broker_acct_asof_idx'),
        ),
        migrations.AddConstraint(
            model_name='wheelbrokeraccountsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('settled_cash__isnull', True), ('settled_cash__gte', 0), _connector='OR'), models.Q(('unsettled_cash__isnull', True), ('unsettled_cash__gte', 0), _connector='OR'), models.Q(('nav__isnull', True), ('nav__gte', 0), _connector='OR'), models.Q(('reserved_cash__isnull', True), ('reserved_cash__gte', 0), _connector='OR'), models.Q(('margin_loan_balance__isnull', True), ('margin_loan_balance__gte', 0), _connector='OR')), name='wheel_broker_non_negative_amounts'),
        ),
        migrations.AddIndex(
            model_name='wheelmarketsnapshot',
            index=models.Index(fields=['underlying', 'source_as_of'], name='wheel_mkt_sec_asof_idx'),
        ),
        migrations.AddConstraint(
            model_name='wheelmarketsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('last_price__isnull', True), ('last_price__gt', 0), _connector='OR'), name='wheel_mkt_last_price_positive'),
        ),
        migrations.AddIndex(
            model_name='wheeloptionquotesnapshot',
            index=models.Index(fields=['underlying', 'expiration', 'strike'], name='wheel_opt_sec_exp_stk_idx'),
        ),
        migrations.AddIndex(
            model_name='wheeloptionquotesnapshot',
            index=models.Index(fields=['provider', 'provider_contract_code'], name='wheel_opt_prov_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='wheeloptionquotesnapshot',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_contract_code', 'quote_as_of'), name='unique_wheel_opt_prov_code_asof'),
        ),
        migrations.AddConstraint(
            model_name='wheeloptionquotesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('strike__gt', 0)), name='wheel_opt_strike_positive'),
        ),
        migrations.AddConstraint(
            model_name='wheeloptionquotesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('deliverable_shares__isnull', True), ('deliverable_shares__gt', 0), _connector='OR'), name='wheel_opt_deliverable_positive'),
        ),
        migrations.AddConstraint(
            model_name='wheeloptionquotesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('contract_multiplier__isnull', True), ('contract_multiplier__gt', 0), _connector='OR'), name='wheel_opt_multiplier_positive'),
        ),
        migrations.AddConstraint(
            model_name='wheeloptionquotesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('bid__isnull', True), ('bid__gte', 0), _connector='OR'), name='wheel_opt_bid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wheeloptionquotesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('ask__isnull', True), ('ask__gte', 0), _connector='OR'), name='wheel_opt_ask_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wheeloptionquotesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('bid__isnull', True), ('ask__isnull', True), ('ask__gte', models.F('bid')), _connector='OR'), name='wheel_opt_ask_ge_bid'),
        ),
        migrations.AddConstraint(
            model_name='wheeloptionquotesnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('assignment_probability__isnull', True), models.Q(('assignment_probability__gte', 0), ('assignment_probability__lte', 100)), _connector='OR'), name='wheel_opt_prob_range'),
        ),
        migrations.AddIndex(
            model_name='wheelcandidate',
            index=models.Index(fields=['decision', 'status'], name='wheel_cand_dec_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='wheelcandidate',
            constraint=models.UniqueConstraint(fields=('decision', 'candidate_key'), name='unique_wheel_cand_dec_key'),
        ),
        migrations.AddConstraint(
            model_name='wheelcandidate',
            constraint=models.CheckConstraint(condition=models.Q(('assignment_probability__isnull', True), models.Q(('assignment_probability__gte', 0), ('assignment_probability__lte', 100)), _connector='OR'), name='wheel_cand_prob_range'),
        ),
        migrations.AddConstraint(
            model_name='wheelcandidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'executable'), _negated=True), models.Q(('annualized_premium_rate__gt', 0), ('assignment_probability__isnull', False), ('break_even__gte', 0), ('contract_count__gte', 1), ('option_quote__isnull', False), ('premium_total__gt', 0), ('required_cash__gt', 0), ('strategy', 'sell_put')), _connector='OR'), name='wheel_cand_executable_fields'),
        ),
        migrations.AddConstraint(
            model_name='wheelpolicy',
            constraint=models.UniqueConstraint(fields=('family', 'account', 'underlying'), name='unique_wheel_policy_family_account_underlying'),
        ),
        migrations.AddConstraint(
            model_name='wheelpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('preferred_premium_min__gte', 0), ('preferred_premium_max__gte', models.F('preferred_premium_min'))), name='wheel_policy_premium_order'),
        ),
        migrations.AddConstraint(
            model_name='wheelpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('preferred_dte_min__gte', 1), ('preferred_dte_max__gte', models.F('preferred_dte_min'))), name='wheel_policy_dte_order'),
        ),
        migrations.AddConstraint(
            model_name='wheelpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('max_underlying_nav_ratio__gt', 0), ('max_underlying_nav_ratio__lte', 1)), name='wheel_policy_nav_ratio_range'),
        ),
        migrations.AddConstraint(
            model_name='wheelpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('max_spread_ratio__gte', 0), ('max_spread_ratio__lte', 1)), name='wheel_policy_spread_ratio_range'),
        ),
        migrations.AddConstraint(
            model_name='wheelpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('account_snapshot_max_age_minutes__gt', 0)), name='wheel_policy_account_age_positive'),
        ),
        migrations.AddConstraint(
            model_name='wheelpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('quote_max_age_seconds__gt', 0)), name='wheel_policy_quote_age_positive'),
        ),
        migrations.AddIndex(
            model_name='wheeldecision',
            index=models.Index(fields=['family', 'underlying', 'decision_time'], name='wheel_dec_fam_sec_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='wheeldecision',
            constraint=models.UniqueConstraint(fields=('family', 'account', 'underlying', 'input_fingerprint'), name='unique_wheel_dec_fam_acct_fp'),
        ),
        migrations.AddConstraint(
            model_name='wheeldecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('overall_status', 'executable'), _negated=True), models.Q(('event_status', 'clear'), ('execution_gate_open', True), ('technical_status', 'complete')), _connector='OR'), name='wheel_dec_executable_gate'),
        ),
    ]
