# Generated by Django 5.2.16 on 2026-08-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('option_wheel', '0001_initial'),
        ('portfolio', '0027_watchlistgroup_watchlistitem_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelbrokeraccountsnapshot',
            name='source_kind',
            field=models.CharField(choices=[('manual_file', '手工文件'), ('portfolio_readonly', '投资组合只读'), ('zhifu_readonly', '致富只读'), ('ibkr_readonly', 'IBKR 只读')], max_length=30, verbose_name='来源类型'),
        ),
        migrations.AddConstraint(
            model_name='wheelbrokeraccountsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('source_reference', ''), _negated=True), fields=('family', 'account', 'source_kind', 'source_reference'), name='wheel_broker_snapshot_source_unique'),
        ),
    ]
