# Generated by Django 5.2.16 on 2026-08-31 15:33

import django.db.models.deletion
import django.utils.timezone
import option_wheel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('option_wheel', '0002_alter_wheelbrokeraccountsnapshot_source_kind_and_more'),
        ('portfolio', '0027_watchlistgroup_watchlistitem_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('open', '进行中'), ('paused', '已暂停'), ('closed', '已结束')], default='open', max_length=20, verbose_name='状态')),
                ('opened_on', models.DateField(verbose_name='开始日期')),
                ('closed_on', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('assigned_cost_basis', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='指派/买入成本')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_cycles', to='portfolio.investmentaccount')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_cycles', to='family_core.family')),
                ('underlying', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_cycles', to='portfolio.security')),
            ],
            options={
                'verbose_name': '车轮周期',
                'verbose_name_plural': '车轮周期',
            },
        ),
        migrations.CreateModel(
            name='WheelEventSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='来源')),
                ('window_start', models.DateField(verbose_name='窗口开始')),
                ('window_end', models.DateField(verbose_name='窗口结束')),
                ('earnings_status', models.CharField(choices=[('clear', '通过'), ('blocked', '阻断'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='财报状态')),
                ('earnings_at', models.DateTimeField(blank=True, null=True, verbose_name='财报时间')),
                ('dividend_status', models.CharField(choices=[('clear', '通过'), ('blocked', '阻断'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='除息状态')),
                ('ex_dividend_date', models.DateField(blank=True, null=True, verbose_name='除息日')),
                ('source_as_of', models.DateTimeField(verbose_name='来源时点')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='获取时间')),
                ('raw_evidence', models.JSONField(blank=True, default=dict, verbose_name='原始证据')),
                ('underlying', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_event_snapshots', to='portfolio.security')),
            ],
            options={
                'verbose_name': '事件快照',
                'verbose_name_plural': '事件快照',
            },
            bases=(option_wheel.models.AppendOnlyEvidenceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WheelLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sequence', models.PositiveIntegerField(verbose_name='顺序')),
                ('strategy', models.CharField(choices=[('sell_put', '卖出看跌'), ('covered_call', '备兑看涨'), ('roll', '滚动'), ('wait', '等待')], max_length=20, verbose_name='策略')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('open', '持仓中'), ('closed', '已平仓'), ('assigned', '已指派'), ('expired', '已到期'), ('cancelled', '已取消')], default='planned', max_length=20, verbose_name='状态')),
                ('expiration', models.DateField(blank=True, null=True, verbose_name='到期日')),
                ('strike', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='行权价')),
                ('contract_count', models.PositiveIntegerField(default=1, verbose_name='合约数')),
                ('premium_total', models.DecimalField(decimal_places=4, default=0, max_digits=24, verbose_name='累计权利金')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='开仓时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legs', to='option_wheel.wheelcycle')),
                ('option_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wheel_legs', to='option_wheel.wheeloptionquotesnapshot')),
                ('parent_leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rolled_legs', to='option_wheel.wheelleg')),
            ],
            options={
                'verbose_name': '车轮分段',
                'verbose_name_plural': '车轮分段',
                'ordering': ['cycle', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='WheelCollateralReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('kind', models.CharField(choices=[('cash', '现金'), ('shares', '股票')], max_length=10, verbose_name='类型')),
                ('currency', models.CharField(blank=True, max_length=10, verbose_name='币种')),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True, verbose_name='现金金额')),
                ('share_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, verbose_name='股票数量')),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='预留时间')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='释放时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_collateral_reservations', to='portfolio.investmentaccount')),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collateral_reservations', to='option_wheel.wheelleg')),
            ],
            options={
                'verbose_name': '车轮担保预留',
                'verbose_name_plural': '车轮担保预留',
            },
        ),
        migrations.CreateModel(
            name='WheelMarketRegimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='来源')),
                ('regime', models.CharField(max_length=30, verbose_name='市场状态')),
                ('source_as_of', models.DateTimeField(verbose_name='来源时点')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='获取时间')),
                ('status', models.CharField(choices=[('complete', '完整'), ('partial', '部分'), ('invalid', '无效')], default='partial', max_length=20, verbose_name='数据状态')),
                ('vix', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='VIX')),
                ('raw_evidence', models.JSONField(blank=True, default=dict, verbose_name='原始证据')),
            ],
            options={
                'verbose_name': '市场环境快照',
                'verbose_name_plural': '市场环境快照',
                'indexes': [models.Index(fields=['-source_as_of'], name='wheel_regime_asof_idx')],
            },
            bases=(option_wheel.models.AppendOnlyEvidenceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WheelPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='暂停开始')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='暂停结束')),
                ('reason', models.TextField(verbose_name='暂停原因')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wheel_pauses', to='portfolio.investmentaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_pauses', to='family_core.family')),
                ('underlying', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wheel_pauses', to='portfolio.security')),
            ],
            options={
                'verbose_name': '车轮暂停',
                'verbose_name_plural': '车轮暂停',
            },
        ),
        migrations.CreateModel(
            name='WheelTechnicalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='来源')),
                ('source_as_of', models.DateTimeField(verbose_name='来源时点')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='获取时间')),
                ('sample_count', models.PositiveIntegerField(default=0, verbose_name='样本数')),
                ('sma_20', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='20 日均线')),
                ('sma_50', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='50 日均线')),
                ('rsi_14', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='14 日 RSI')),
                ('atr_14', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='14 日 ATR')),
                ('return_5d', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='5 日收益率')),
                ('return_20d', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='20 日收益率')),
                ('status', models.CharField(choices=[('complete', '完整'), ('partial', '部分'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='状态')),
                ('raw_evidence', models.JSONField(blank=True, default=dict, verbose_name='原始证据')),
                ('underlying', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_technical_snapshots', to='portfolio.security')),
            ],
            options={
                'verbose_name': '技术分析快照',
                'verbose_name_plural': '技术分析快照',
            },
            bases=(option_wheel.models.AppendOnlyEvidenceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WheelTransactionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.CharField(max_length=30, verbose_name='关联角色')),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_links', to='option_wheel.wheelleg')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_link', to='portfolio.investmenttransaction')),
            ],
            options={
                'verbose_name': '车轮交易关联',
                'verbose_name_plural': '车轮交易关联',
            },
        ),
        migrations.AddConstraint(
            model_name='wheelcycle',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'paused'])), fields=('account', 'underlying'), name='unique_active_wheel_cycle'),
        ),
        migrations.AddIndex(
            model_name='wheeleventsnapshot',
            index=models.Index(fields=['underlying', '-source_as_of'], name='wheel_event_under_asof_idx'),
        ),
        migrations.AddConstraint(
            model_name='wheelleg',
            constraint=models.UniqueConstraint(fields=('cycle', 'sequence'), name='unique_wheel_leg_sequence'),
        ),
        migrations.AddConstraint(
            model_name='wheelcollateralreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('leg',), name='unique_active_leg_collateral'),
        ),
        migrations.AddConstraint(
            model_name='wheelcollateralreservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cash_amount__gt', 0), ('kind', 'cash'), ('share_quantity__isnull', True)), models.Q(('cash_amount__isnull', True), ('kind', 'shares'), ('share_quantity__gt', 0)), _connector='OR'), name='wheel_collateral_kind_amount'),
        ),
        migrations.AddIndex(
            model_name='wheelpause',
            index=models.Index(fields=['family', 'starts_at', 'ends_at'], name='wheel_pause_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='wheeltechnicalsnapshot',
            index=models.Index(fields=['underlying', '-source_as_of'], name='wheel_tech_under_asof_idx'),
        ),
    ]
