# Generated by Django 5.2.16 on 2026-08-31 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_wheel', '0003_wheelcycle_wheeleventsnapshot_wheelleg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheeldecision',
            name='event_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='option_wheel.wheeleventsnapshot', verbose_name='事件快照'),
        ),
        migrations.AddField(
            model_name='wheeldecision',
            name='market_regime_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='option_wheel.wheelmarketregimesnapshot', verbose_name='市场环境快照'),
        ),
        migrations.AddField(
            model_name='wheeldecision',
            name='technical_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='option_wheel.wheeltechnicalsnapshot', verbose_name='技术快照'),
        ),
    ]
