# Generated by Django 5.2.16 on 2026-09-01 10:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('option_wheel', '0004_wheeldecision_event_snapshot_and_more'),
        ('portfolio', '0028_optioncontract_is_adjusted_optioncontract_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelcycle',
            name='assigned_share_quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24, verbose_name='本周期持有正股数量'),
        ),
        migrations.AddField(
            model_name='wheelleg',
            name='open_contract_count',
            field=models.PositiveIntegerField(default=1, verbose_name='未平合约数'),
        ),
        migrations.AddField(
            model_name='wheeltransactionlink',
            name='linked_quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=24, verbose_name='关联期权张数'),
        ),
        migrations.AlterField(
            model_name='wheeltransactionlink',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_links', to='portfolio.investmenttransaction'),
        ),
        migrations.AddConstraint(
            model_name='wheelcycle',
            constraint=models.CheckConstraint(condition=models.Q(('assigned_share_quantity__gte', 0)), name='wheel_cycle_shares_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wheeltransactionlink',
            constraint=models.UniqueConstraint(fields=('leg', 'transaction', 'role'), name='unique_wheel_leg_txn_role'),
        ),
        migrations.AddConstraint(
            model_name='wheeltransactionlink',
            constraint=models.CheckConstraint(condition=models.Q(('linked_quantity__gt', 0)), name='wheel_txn_link_qty_positive'),
        ),
    ]
