# Generated by Django 5.2.16 on 2026-09-01 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_wheel', '0005_wheelcycle_assigned_share_quantity_and_more'),
        ('portfolio', '0028_optioncontract_is_adjusted_optioncontract_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelleg',
            name='option_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wheel_legs', to='portfolio.optioncontract'),
        ),
    ]
