# Generated by Django 5.2.16 on 2026-09-03 05:27

import django.db.models.deletion
import option_wheel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('option_wheel', '0006_wheelleg_option_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelCloseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('symbol', models.CharField(max_length=12)),
                ('target_date', models.DateField()),
                ('request_key', models.UUIDField()),
                ('evidence', models.JSONField(default=dict)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family_core.family')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('family', 'request_key'), name='wheel_close_request_unique')],
            },
            bases=(option_wheel.models.AppendOnlyEvidenceMixin, models.Model),
        ),
    ]
