# Generated by Django 5.2.16 on 2026-09-22 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_core', '0008_assetcategory_code_constraint'),
        ('option_wheel', '0011_wheel_watch_and_screening'),
        ('portfolio', '0028_optioncontract_is_adjusted_optioncontract_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelPositionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('choice', models.CharField(choices=[('hold', '继续持有'), ('buy_back', '考虑买回'), ('roll_out', '考虑同价延后'), ('roll_down_out', '考虑降价延后'), ('assignment', '等待核实指派'), ('pause', '暂停操作')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('frozen_facts', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_position_reviews', to='portfolio.investmentaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_position_reviews', to='family_core.family')),
                ('linked_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wheel_position_reviews', to='portfolio.investmenttransaction')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_position_reviews', to='portfolio.security')),
            ],
            options={
                'verbose_name': '车轮人工决策记录',
                'verbose_name_plural': '车轮人工决策记录',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
